import type { Language } from "@/lib/languages";

const LANGS = ["en", "de", "es", "fr", "sq", "pl", "ro", "bg", "ka", "ar", "uk", "ru", "zh"] as const satisfies readonly Language[];
type L = Record<Language, string>;
function L(...values: readonly string[]): L {
  const out = {} as L;
  LANGS.forEach((lang, i) => { out[lang] = values[i] ?? values[0] ?? ""; });
  return out;
}

type Section = { h: L; p: L };
type BlogArticle = {
  id: string;
  minutes: number;
  slug: L;
  title: L;
  description: L;
  kicker: L;
  sections: Section[];
};

export const BLOG_REST: BlogArticle[] = [
  {
    id: "read-vin",
    minutes: 5,
    kicker: L("VIN", "VIN", "VIN", "VIN", "VIN", "VIN", "VIN", "VIN", "VIN", "VIN", "VIN", "VIN", "VIN"),
    slug: L("how-to-read-a-vin", "vin-lesen", "como-leer-un-vin", "lire-un-vin", "si-te-lexosh-nje-vin", "jak-czytac-vin", "cum-citesti-un-vin", "kak-da-cheteme-vin", "rogor-tsakitkhot-vin", "kayfa-taqra-vin", "yak-chytaty-vin", "kak-chitat-vin", "ruhe-du-vin"),
    title: L(
      "How to read a VIN before you buy",
      "VIN lesen, bevor Sie kaufen",
      "Cómo leer un VIN antes de comprar",
      "Lire un VIN avant d'acheter",
      "Si ta lexosh VIN-in para se të blesh",
      "Jak czytać VIN, zanim kupisz",
      "Cum citești un VIN înainte să cumperi",
      "Как да четете VIN, преди да купите",
      "როგორ წაიკითხოთ VIN ყიდვამდე",
      "كيف تقرأ رقم الهيكل قبل الشراء",
      "Як читати VIN перед покупкою",
      "Как читать VIN перед покупкой",
      "买车前怎么读 VIN",
    ),
    description: L(
      "A VIN is 17 characters. The first digits name the maker and the plant. The rest is the car, not its history.",
      "Eine VIN hat 17 Zeichen. Die ersten Ziffern nennen Hersteller und Werk. Der Rest ist das Auto, nicht seine Geschichte.",
      "Un VIN tiene 17 caracteres. Los primeros dicen el fabricante y la planta. El resto es el coche, no su historia.",
      "Un VIN a 17 caractères. Les premiers disent le constructeur et l'usine. Le reste est la voiture, pas son histoire.",
      "VIN-i ka 17 shenja. Të parat tregojnë prodhuesin dhe fabrikën. Pjesa tjetër është makina, jo historia e saj.",
      "VIN ma 17 znaków. Pierwsze podają producenta i fabrykę. Reszta to auto, nie jego historia.",
      "VIN-ul are 17 caractere. Primele spun producătorul și fabrica. Restul e mașina, nu istoricul ei.",
      "VIN има 17 знака. Първите казват производителя и завода. Останалото е колата, не историята ѝ.",
      "VIN 17 ნიშანია. პირველები ასახელებენ მწარმოებელსა და ქარხანას. დანარჩენი მანქანაა, არა მისი ისტორია.",
      "رقم الهيكل 17 رمزاً. أوله يسمي الصانع والمصنع. الباقي هو السيارة، لا تاريخها.",
      "VIN має 17 знаків. Перші називають виробника і завод. Решта це авто, не його історія.",
      "VIN состоит из 17 знаков. Первые называют производителя и завод. Остальное это машина, не её история.",
      "VIN 有 17 位。前面几位是厂家和工厂。后面是这辆车，不是它的历史。",
    ),
    sections: [
      {
        h: L("Where the number sits", "Wo die Nummer steht", "Dónde está el número", "Où se trouve le numéro", "Ku e gjen numrin", "Gdzie jest numer", "Unde stă numărul", "Къде стои номерът", "სად დგას ნომერი", "أين يوجد الرقم", "Де стоїть номер", "Где стоит номер", "号码在哪里"),
        p: L(
          "Look at the base of the windscreen, the door jamb and the paperwork. All three should match. A plate that does not match the one stamped on the body is a reason to walk away before you talk about price.",
          "Schauen Sie an den unteren Rand der Scheibe, in die Türöffnung und auf die Papiere. Alle drei müssen übereinstimmen. Ein Schild, das nicht zur Prägung an der Karosserie passt, ist ein Grund zu gehen, bevor Sie über den Preis reden.",
          "Mira la base del parabrisas, el marco de la puerta y los papeles. Los tres deben coincidir. Una placa que no coincide con la grabada en la carrocería es motivo para irte antes de hablar de precio.",
          "Regardez le bas du pare-brise, l'encadrement de porte et les papiers. Les trois doivent correspondre. Une plaque qui ne correspond pas à celle frappée sur la caisse est une raison de partir avant de parler prix.",
          "Shiko bazën e xhamit, kornizën e derës dhe dokumentet. Të treja duhet të përputhen. Një targë që nuk përputhet me numrin e stampuar në karroceri është arsye të largohesh para se të flasësh për çmimin.",
          "Spójrz na podstawę szyby, słupek drzwi i dokumenty. Wszystkie trzy muszą się zgadzać. Tabliczka, która nie pasuje do wybicia na karoserii, to powód, żeby odejść, zanim zaczniesz o cenę.",
          "Uită-te la baza parbrizului, la stâlpul ușii și la acte. Toate trei trebuie să coincidă. O plăcuță care nu se potrivește cu numărul ștanțat pe caroserie e un motiv să pleci înainte să vorbești de preț.",
          "Вижте основата на стъклото, касата на вратата и документите. И трите трябва да съвпадат. Табела, която не съвпада с щампования номер по купето, е причина да си тръгнете, преди да говорите за цена.",
          "ნახეთ მინის ძირი, კარის ღიობი და ქაღალდები. სამივე უნდა ემთხვეოდეს. ფირფიტა, რომელიც ძარაზე დატანილ ნომერს არ ემთხვევა, საკმარისი მიზეზია, ფასზე საუბრამდე წახვიდეთ.",
          "انظر أسفل الزجاج الأمامي وإطار الباب والأوراق. يجب أن تتطابق الثلاثة. لوحة لا تطابق الرقم المختوم على الهيكل سبب للمغادرة قبل الحديث عن السعر.",
          "Подивіться на низ скла, на стійку дверей і на папери. Усі три мають збігатися. Табличка, яка не збігається з номером на кузові, це привід піти, перш ніж говорити про ціну.",
          "Посмотрите на низ стекла, на стойку двери и на бумаги. Все три должны совпадать. Табличка, которая не совпадает с номером на кузове, это повод уйти до разговора о цене.",
          "看风挡下沿、门框和文件。三处应该一致。铭牌和车身打码对不上，在谈价格之前就该走。",
        ),
      },
      {
        h: L("What the VIN does not tell you", "Was die VIN nicht verrät", "Lo que el VIN no te dice", "Ce que le VIN ne dit pas", "VIN-i nuk tregon historinë", "Czego VIN ci nie powie", "Ce nu îți spune VIN-ul", "Какво VIN не ти казва", "რას არ გეუბნებათ VIN", "ما لا يقوله رقم الهيكل", "Чого VIN не скаже", "Чего VIN не скажет", "VIN 不会告诉你的"),
        p: L(
          "The VIN identifies the car as it left the factory. It does not store later crashes, a new odometer or a salvage ruling. Those come from later records. Read the number so you check the right car, then open the history before you pay.",
          "Die VIN benennt das Auto, wie es das Werk verlassen hat. Spätere Unfälle, ein neuer Tacho oder eine Totalschaden-Entscheidung stehen nicht darin. Die kommen aus späteren Akten. Lesen Sie die Nummer, damit Sie das richtige Auto prüfen, und öffnen Sie die Historie, bevor Sie zahlen.",
          "El VIN identifica el coche tal como salió de fábrica. No guarda choques posteriores, un cuentakilómetros nuevo ni una pérdida total. Eso llega en registros posteriores. Lee el número para comprobar el coche correcto y abre el historial antes de pagar.",
          "Le VIN identifie la voiture telle qu'elle a quitté l'usine. Il ne garde pas les chocs plus tard, un compteur neuf ou une perte totale. Cela vient de dossiers ultérieurs. Lisez le numéro pour contrôler la bonne voiture, puis ouvrez l'historique avant de payer.",
          "VIN-i e identifikon makinën ashtu si doli nga fabrika. Nuk ruan përplasjet e mëvonshme, një kilometrazh të ri apo një dëmtim total. Ato vijnë nga regjistra të mëvonshëm. Lexoje numrin që të kontrollosh makinën e duhur, pastaj hape historinë para se të paguash.",
          "VIN identyfikuje auto takie, jakie wyjechało z fabryki. Nie trzyma późniejszych stłuczek, nowego licznika ani szkody całkowitej. To przychodzi z późniejszych zapisów. Odczytaj numer, żeby sprawdzić właściwe auto, i otwórz historię, zanim zapłacisz.",
          "VIN-ul identifică mașina așa cum a ieșit din fabrică. Nu păstrează loviturile de mai târziu, un kilometraj nou sau o daună totală. Acelea vin din înregistrări ulterioare. Citește numărul ca să verifici mașina corectă, apoi deschide istoricul înainte să plătești.",
          "VIN идентифицира колата така, както е излязла от завода. Не пази по-късни удари, нов километраж или тотална щета. Те идват от по-късни записи. Прочетете номера, за да проверите правилната кола, и отворете историята, преди да платите.",
          "VIN ასახელებს მანქანას ისე, როგორც ქარხნიდან გამოვიდა. მოგვიანებითი დარტყმები, ახალი კილომეტრაჟი ან სალვაჟი მასში არ ინახება. ისინი გვიანდელი ჩანაწერებიდან მოდის. წაიკითხეთ ნომერი, რომ სწორი მანქანა შეამოწმოთ, და ისტორია გადახდამდე გახსენით.",
          "رقم الهيكل يعرّف السيارة كما خرجت من المصنع. لا يخزّن حوادث لاحقة ولا عداداً جديداً ولا خسارة كاملة. تلك تأتي من سجلات لاحقة. اقرأ الرقم لتفحص السيارة الصحيحة، ثم افتح التاريخ قبل أن تدفع.",
          "VIN називає авто таким, яким воно вийшло з заводу. Пізніші удари, новий одометр чи тотал у ньому не зберігаються. Вони приходять із пізніших записів. Прочитайте номер, щоб перевірити правильне авто, і відкрийте історію до оплати.",
          "VIN называет машину такой, какой она вышла с завода. Поздние удары, новый одометр или тотал в нём не хранятся. Они приходят из поздних записей. Прочитайте номер, чтобы проверить правильную машину, и откройте историю до оплаты.",
          "VIN 只标明这辆车出厂时是谁。后来的事故、换过的里程表、全损判定都不在里面。那些在后来的记录里。先读对号码，确认查的是这辆车，再在付款前打开历史。",
        ),
      },
    ],
  },
  {
    id: "rollback",
    minutes: 6,
    kicker: L("Odometer", "Tacho", "Cuentakilómetros", "Compteur", "Kilometrazhi", "Licznik", "Kilometraj", "Километраж", "კილომეტრაჟი", "العداد", "Одометр", "Одометр", "里程表"),
    slug: L("odometer-rollback", "tacho-zurueckgestellt", "cuentakilometros-atrasado", "compteur-recule", "kilometrazh-i-kthyer", "cofnięty-licznik", "kilometraj-dat-inapoi", "varnat-kilometrazh", "ukandabrunebuli-kilometrazhi", "adad-muraja", "skruchenyy-probig", "skruchennyy-probeg", "licheng-huitui"),
    title: L(
      "When the odometer goes backwards",
      "Wenn der Tacho rückwärts läuft",
      "Cuando el cuentakilómetros va hacia atrás",
      "Quand le compteur recule",
      "Kur kilometrazhi kthehet mbrapsht",
      "Kiedy licznik cofa się",
      "Când kilometrajul dă înapoi",
      "Когато километражът се връща назад",
      "როცა კილომეტრაჟი უკან ბრუნდება",
      "عندما يرجع العداد للخلف",
      "Коли одометр іде назад",
      "Когда одометр идёт назад",
      "里程表往回走的时候",
    ),
    description: L(
      "A lower number than an earlier record is the classic rollback. The advert will not mention the jump.",
      "Eine kleinere Zahl als in einem älteren Beleg ist der klassische Rücklauf. Die Anzeige erwähnt den Sprung nicht.",
      "Un número más bajo que un registro anterior es el clásico atraso. El anuncio no menciona el salto.",
      "Un chiffre plus bas qu'un relevé plus ancien est le recul classique. L'annonce ne mentionne pas le saut.",
      "Një shifër më e vogël se ajo e mëparshmja do të thotë se kilometrat janë kthyer. Shpallja s'të thotë këtë.",
      "Niższa liczba niż wcześniejszy zapis to klasyczne cofnięcie. Ogłoszenie nie wspomni o skoku.",
      "Un număr mai mic decât o citire mai veche e întoarcerea clasică. Anunțul nu menționează saltul.",
      "По-малко число от по-ранен запис е класическото връщане. Обявата няма да спомене скока.",
      "უფრო დაბალი რიცხვი, ვიდრე ადრინდელი ჩანაწერი, კლასიკური უკან დაბრუნებაა. განცხადება ნახტომს არ ახსენებს.",
      "رقم أقل من قراءة أقدم هو التراجع الكلاسيكي. الإعلان لن يذكر القفزة.",
      "Менше число, ніж у давнішому записі, це класичне скручування. Оголошення не згадає стрибок.",
      "Число меньше, чем в более ранней записи, это классическое скручивание. Объявление не упомянет скачок.",
      "比更早的记录还低的数字，就是典型的回表。广告不会提这个落差。",
    ),
    sections: [
      {
        h: L("The number has to go forward", "Die Zahl muss nach vorn", "El número tiene que avanzar", "Le chiffre doit avancer", "Kilometrat vetëm rriten", "Liczba musi iść do przodu", "Numărul trebuie să meargă înainte", "Числото трябва да върви напред", "რიცხვი წინ უნდა მიდიოდეს", "الرقم يجب أن يتقدم", "Число має йти вперед", "Число должно идти вперёд", "数字只能往前走"),
        p: L(
          "A car collects kilometres. If an auction sheet from two years ago shows 180,000 and the seller says 110,000 today, the odometer was moved or replaced. Wear on the wheel, the pedals and the driver's seat will not match a low number. The logged reading is what matters, not the story.",
          "Ein Auto sammelt Kilometer. Zeigt ein Auktionsbogen von vor zwei Jahren 180.000 und der Verkäufer sagt heute 110.000, wurde der Tacho bewegt oder getauscht. Verschleiß an Lenkrad, Pedalen und Sitz passt nicht zu einer kleinen Zahl. Die gespeicherte Ablesung zählt, nicht die Geschichte.",
          "Un coche acumula kilómetros. Si una ficha de subasta de hace dos años marca 180.000 y el vendedor dice 110.000 hoy, el cuentakilómetros se movió o se cambió. El desgaste del volante, los pedales y el asiento no encaja con un número bajo. La lectura registrada es la que cuenta, no el relato.",
          "Une voiture accumule des kilomètres. Si une fiche d'enchère d'il y a deux ans indique 180 000 et que le vendeur dit 110 000 aujourd'hui, le compteur a été reculé ou changé. L'usure du volant, des pédales et du siège ne correspond pas à un petit chiffre. Le relevé enregistré compte, pas le récit.",
          "Makina mbledh kilometra. Nëse fleta e ankandit dy vjet më parë tregon 180.000 dhe shitësi thotë 110.000 sot, kilometrazhi është lëvizur ose ndërruar. Konsumimi i timonit, pedaleve dhe ndenjëses nuk përputhet me një shifër të ulët. Leximi i regjistruar është ai që vlen, jo rrëfimi.",
          "Auto zbiera kilometry. Jeśli karta aukcyjna sprzed dwóch lat pokazuje 180 000, a sprzedawca mówi dziś 110 000, licznik ruszyli albo wymienili. Zużycie kierownicy, pedałów i fotela nie pasuje do niskiej liczby. Liczy się zapisany odczyt, nie opowieść.",
          "Mașina adună kilometri. Dacă fișa de licitație de acum doi ani arată 180.000 și vânzătorul spune 110.000 azi, kilometrajul a fost mutat sau schimbat. Uzura volanului, a pedalelor și a scaunului nu se potrivește cu un număr mic. Citirea înregistrată contează, nu povestea.",
          "Колата събира километри. Ако тържен лист отпреди две години показва 180 000, а продавачът казва 110 000 днес, километражът е местен или сменен. Износването на волана, педалите и седалката не пасва на ниско число. Записаното отчитане е важното, не историята.",
          "მანქანა კილომეტრებს აგროვებს. თუ ორი წლის წინანდელი აუქციონის ფურცელი 180 000-ს აჩვენებს და გამყიდველი დღეს 110 000-ს ამბობს, კილომეტრაჟი გადაადგილებულია ან შეცვლილია. საჭის, პედლებისა და სავარძლის ცვეთა დაბალ რიცხვს არ ემთხვევა. ჩაწერილი წაკითხვა მნიშვნელოვანია, არა ამბავი.",
          "السيارة تجمع الكيلومترات. إذا أظهرت ورقة مزاد قبل سنتين 180 ألفاً والبائع يقول 110 آلاف اليوم، فقد حُرّك العداد أو استُبدل. تآكل المقود والدواسات والمقعد لا يطابق رقماً منخفضاً. القراءة المسجّلة هي المهمة، لا الحكاية.",
          "Авто збирає кілометри. Якщо аукціонний лист двох років тому показує 180 000, а продавець сьогодні каже 110 000, одометр зрушили або замінили. Знос керма, педалей і сидіння не сходиться з малим числом. Важливий записаний показник, не розповідь.",
          "Машина копит километры. Если аукционный лист двухлетней давности показывает 180 000, а продавец сегодня говорит 110 000, одометр сдвинули или заменили. Износ руля, педалей и сиденья не сходится с малым числом. Важна записанная цифра, не рассказ.",
          "车只会把公里越加越多。如果两年前的拍卖单是 18 万，卖家今天说 11 万，里程表被改过或换过。方向盘、踏板和驾驶座的磨损对不上这个低数字。记下的读数才算数，故事不算。",
        ),
      },
      {
        h: L("Why that kilometre gap costs you", "Warum dich die Differenz Geld kostet", "Por qué esa diferencia te sale cara", "Pourquoi cet écart vous coûte cher", "Pse të del shtrenjtë ky ndryshim", "Dlaczego ta różnica kosztuje", "De ce te costă diferența asta", "Защо тази разлика излиза скъпо", "რატომ გიჯდება ეს სხვაობა", "لماذا يكلفك هذا الفرق", "Чому ця різниця коштує", "Почему эта разница вам дорого обходится", "这个公里差为什么贵"),
        p: L(
          "Parts wear by distance, not by the number the seller prefers. You pay for a clutch, a turbo or a suspension that already did the kilometres hidden in the gap. Seeing the earlier reading before you agree on a price is the whole point of the report.",
          "Teile verschleißen nach Strecke, nicht nach der Zahl, die der Verkäufer mag. Sie zahlen für eine Kupplung, einen Turbo oder ein Fahrwerk, das die versteckten Kilometer schon gefahren ist. Die ältere Ablesung zu sehen, bevor Sie den Preis zusagen, ist der Sinn des Berichts.",
          "Las piezas se gastan por distancia, no por el número que prefiere el vendedor. Pagas un embrague, un turbo o una suspensión que ya recorrió los kilómetros ocultos. Ver la lectura anterior antes de cerrar el precio es el sentido del informe.",
          "Les pièces s'usent selon la distance, pas selon le chiffre que préfère le vendeur. Vous payez un embrayage, un turbo ou une suspension qui a déjà fait les kilomètres cachés. Voir le relevé plus ancien avant d'accepter le prix est tout l'intérêt du rapport.",
          "Pjesët lodhen nga rruga e bërë, jo nga numri që i pëlqen shitësit. Pastaj paguan një friksion, një turbo ose një amortizator që i ka bërë tashmë kilometrat e fshehur. Ta shohësh leximin e mëparshëm para se të biesh dakord për çmimin, pikërisht për këtë është raporti.",
          "Części zużywają się od drogi, nie od liczby, którą woli sprzedawca. Płacisz za sprzęgło, turbinę albo zawieszenie, które już zrobiło ukryte kilometry. Zobaczyć wcześniejszy odczyt, zanim zgodzisz się na cenę, po to właśnie jest raport.",
          "Piesele se uzează după drum, nu după numărul pe care îl vrea vânzătorul. Plătești un ambreiaj, o turbină sau o suspensie care a făcut deja kilometrii ascunși. Să vezi citirea mai veche înainte să accepți prețul este rostul raportului.",
          "Частите се износват от пътя, не от числото, което харесва продавачът. Плащате съединител, турбо или окачване, което вече е изминало скритите километри. Да видите по-ранното отчитане, преди да приемете цена, е смисълът на отчета.",
          "ნაწილები ცვდება გზით, არა იმ რიცხვით, რომელიც გამყიდველს მოსწონს. იხდით დისკს, ტურბოს ან საკიდარს, რომელმაც დამალული კილომეტრები უკვე გაიარა. ფასზე დათანხმებამდე ადრინდელი წაკითხვის ნახვა ანგარიშის აზრია.",
          "القطع تتآكل بالمسافة، لا بالرقم الذي يفضّله البائع. تدفع ثمن فاصل أو توربو أو نظام تعليق قطع الكيلومترات المخفية. رؤية القراءة الأقدم قبل الاتفاق على السعر هي فائدة التقرير.",
          "Деталі зношуються від дороги, не від числа, яке подобається продавцю. Ви платите за зчеплення, турбіну чи підвіску, яка вже проїхала приховані кілометри. Побачити давніший показник до згоди на ціну і є сенс звіту.",
          "Детали изнашиваются от дороги, не от числа, которое нравится продавцу. Вы платите за сцепление, турбину или подвеску, которая уже проехала скрытые километры. Увидеть более раннюю цифру до согласия на цену и есть смысл отчёта.",
          "零件按走过的路磨损，不按卖家喜欢的数字磨损。离合器、涡轮或悬挂往往已经跑完了被藏起来的那些公里。在谈妥价格之前看到更早的读数，就是这份报告要做的事。",
        ),
      },
    ],
  },
  {
    id: "salvage",
    minutes: 5,
    kicker: L("Title", "Titel", "Título", "Titre", "Titulli", "Tytuł", "Titlu", "Титул", "ტიტული", "الملكية", "Титул", "Титул", "产权"),
    slug: L("what-salvage-means", "was-totalschaden-bedeutet", "que-significa-perdida-total", "que-signifie-vehicule-epave", "cfare-do-te-thote-salvage", "co-znaczy-szkoda-calkowita", "ce-inseamna-dauna-totala", "kakvo-oznachava-totalna-shteta", "ras-nishnavs-salvage", "maadha-yanee-al-khasara-al-kamila", "shcho-oznachaye-total", "chto-znachit-total", "shenme-shi-quan-sun"),
    title: L(
      "What a salvage or total-loss title means",
      "Was ein Totalschaden auf dem Titel bedeutet",
      "Qué significa un título de pérdida total",
      "Ce que signifie un véhicule déclaré épave",
      "Kur sigurimi e ka nxjerrë makinën jashtë",
      "Co oznacza tytuł szkody całkowitej",
      "Ce înseamnă un titlu de daună totală",
      "Какво означава титул за тотална щета",
      "რას ნიშნავს სალვაჟის ტიტული",
      "ماذا يعني قرار الخسارة الكاملة",
      "Що означає титул тотала",
      "Что значит титул тотала",
      "全损或报废产权是什么意思",
    ),
    description: L(
      "A salvage brand means an insurer wrote the car off. Paint can hide that. The record does not disappear.",
      "Ein Totalschaden heißt: der Versicherer hat das Auto abgeschrieben. Lack kann das verstecken. Der Eintrag bleibt.",
      "Una pérdida total significa que el seguro dio el coche por perdido. La pintura puede ocultarlo. El registro no se borra.",
      "Une épave signifie qu'un assureur a déclaré la voiture perdue. La peinture peut le cacher. La trace reste.",
      "Kur sigurimi e nxjerr makinën jashtë, kjo mbetet e shënuar. Boja e re nuk e fshin.",
      "Szkoda całkowita znaczy, że ubezpieczyciel spisał auto. Lakier to ukryje. Zapis zostaje.",
      "Dauna totală înseamnă că asigurătorul a casat mașina. Vopseaua o poate ascunde. Înregistrarea rămâne.",
      "Тотална щета значи, че застрахователят е отписал колата. Боята може да го скрие. Записът остава.",
      "სალვაჟი ნიშნავს, რომ მზღვეველმა მანქანა ჩამოწერა. საღებავი ამას მალავს. ჩანაწერი არ ქრება.",
      "الخسارة الكاملة تعني أن المؤمن شطب السيارة. الطلاء قد يخفي ذلك. السجل لا يختفي.",
      "Тотал означає, що страховик списав авто. Фарба це приховає. Запис лишається.",
      "Тотал значит, что страховщик списал машину. Краска это спрячет. Запись остаётся.",
      "全损是指保险公司已经把这辆车报废处理。喷漆可以藏住外观。记录不会消失。",
    ),
    sections: [
      {
        h: L("The insurer already decided", "Der Versicherer hat schon entschieden", "El seguro ya decidió", "L'assureur a déjà décidé", "Sigurimi e ka vendosur tashmë", "Ubezpieczyciel już zdecydował", "Asigurătorul a decis deja", "Застрахователят вече е решил", "მზღვეველმა უკვე გადაწყვიტა", "المؤمن قرر مسبقاً", "Страховик уже вирішив", "Страховщик уже решил", "保险公司已经定了"),
        p: L(
          "Salvage, total loss or a rebuilt title means the repair was judged more expensive than the car. Someone may have fixed it since. The brand stays on the record so the next buyer knows the structure was damaged badly enough for an insurer to walk away.",
          "Totalschaden oder ein wiederaufgebauter Titel heißt: die Reparatur war teurer als das Auto. Jemand kann es seitdem gerichtet haben. Der Vermerk bleibt, damit der nächste Käufer weiß, dass die Struktur schwer genug beschädigt war, dass ein Versicherer ausgestiegen ist.",
          "Pérdida total o un título reconstruido significa que reparar salía más caro que el coche. Alguien pudo arreglarlo después. La marca se queda para que el siguiente sepa que la estructura se dañó lo bastante como para que el seguro renunciara.",
          "Épave ou titre reconstruit : la réparation coûtait plus que la voiture. Quelqu'un a pu la remettre en état. La marque reste pour que l'acheteur suivant sache que la structure a été assez abîmée pour qu'un assureur renonce.",
          "Salvage ose një titull i rindërtuar do të thotë se riparimi doli më shtrenjtë se vetë makina. Dikush mund ta ketë rregulluar pastaj. Shënimi mbetet, që blerësi tjetër ta shohë se makina është dëmtuar aq sa sigurimi është tërhequr.",
          "Szkoda całkowita albo tytuł odbudowany znaczy, że naprawa była droższa niż auto. Ktoś mógł je potem złożyć. Oznaczenie zostaje, żeby następny kupujący wiedział, że konstrukcja ucierpiała na tyle, że ubezpieczyciel odpuścił.",
          "Dauna totală sau un titlu reconstruit înseamnă că reparația a fost judecată mai scumpă decât mașina. Cineva poate a reparat-o apoi. Marca rămâne ca următorul cumpărător să știe că structura a fost destul de lovită încât asigurătorul a renunțat.",
          "Тотална щета или възстановен титул значи, че ремонтът е бил по-скъп от колата. Някой може да я е оправил после. Бележката остава, за да знае следващият купувач, че конструкцията е била достатъчно повредена, та застрахователят да се откаже.",
          "სალვაჟი ან აღდგენილი ტიტული ნიშნავს, რომ რემონტი მანქანაზე ძვირი ჩათვალეს. შეიძლება მერე ვინმემ შეაკეთა. ნიშანი რჩება, რომ შემდეგმა მყიდველმა იცოდეს: კონსტრუქცია ისე დაზიანდა, რომ მზღვეველმა ხელი აიღო.",
          "الخسارة الكاملة أو الملكية المعاد بناؤها تعني أن الإصلاح حُكم أغلى من السيارة. ربما أصلحها أحد بعدها. العلامة تبقى ليعرف المشتري التالي أن الهيكل تضرر بما يكفي ليتركه التأمين.",
          "Тотал або відбудований титул означає, що ремонт визнали дорожчим за авто. Хтось міг потім його зібрати. Позначка лишається, щоб наступний покупець знав: конструкція була пошкоджена настільки, що страховик відмовився.",
          "Тотал или восстановленный титул значит, что ремонт признали дороже машины. Кто-то мог потом её собрать. Отметка остаётся, чтобы следующий покупатель знал: конструкция была повреждена так, что страховщик отказался.",
          "全损或重建产权的意思是：修车比车本身还贵，保险公司放弃了。后来也许有人修过。这个记号会留下来，让下一个买主知道结构曾经伤得够重。",
        ),
      },
      {
        h: L("A shiny car can still carry the brand", "Ein glänzendes Auto kann den Vermerk tragen", "Un coche brillante puede llevar la marca", "Une voiture brillante peut porter la marque", "Një makinë e shkëlqyer mund ta mbajë shënimin", "Lśniące auto może nieść oznaczenie", "O mașină lucioasă poate purta marca", "Лъскава кола може да носи бележката", "ბრწყინვალე მანქანას ნიშანი შეიძლება ჰქონდეს", "سيارة لامعة قد تحمل العلامة", "Блискуче авто може нести позначку", "Блестящая машина может нести отметку", "亮的车照样可能带着这个记号"),
        p: L(
          "Body shops are good at making a written-off car look finished. Doors shut, paint matches, and the advert says one owner. The title brand does not wash off. If you only look at the car in daylight, you will not see it.",
          "Werkstätten können ein abgeschriebenes Auto fertig aussehen lassen. Türen schließen, der Lack passt, die Anzeige sagt ein Vorbesitzer. Der Titelvermerk geht nicht ab. Wer das Auto nur bei Tageslicht anschaut, sieht ihn nicht.",
          "Un taller hace que un coche dado de baja parezca terminado. Las puertas cierran, la pintura coincide y el anuncio dice un dueño. La marca del título no se lava. Si solo miras el coche de día, no la ves.",
          "Un atelier sait faire paraître finie une voiture radiée. Les portes ferment, la peinture va, l'annonce dit un propriétaire. La marque au titre ne part pas au lavage. Si vous ne regardez la voiture qu'au jour, vous ne la voyez pas.",
          "Servisi e bën një makinë të dëmtuar total të duket gati. Dyert mbyllen, boja përputhet, shpallja thotë një pronar. Shënimi i titullit nuk lahet. Nëse e sheh makinën vetëm ditën, nuk e sheh atë.",
          "Warsztat sprawi, że auto po szkodzie całkowitej wygląda na skończone. Drzwi się domykają, lakier pasuje, ogłoszenie mówi jeden właściciel. Oznaczenia tytułu się nie zmywa. Jak oglądasz auto tylko w dzień, tego nie zobaczysz.",
          "Un service face ca o mașină casată să pară gata. Ușile se închid, vopseaua se potrivește, anunțul spune un proprietar. Marca de titlu nu se spală. Dacă te uiți la mașină doar ziua, n-o vezi.",
          "Сервизът прави отписана кола да изглежда готова. Вратите се затварят, боята пасва, обявата казва един собственик. Бележката по титула не се измива. Ако гледате колата само на дневна светлина, няма да я видите.",
          "სერვისი ჩამოწერილ მანქანას დასრულებულს ხდის. კარები იკეტება, საღებავი ემთხვევა, განცხადება ერთ მფლობელს ამბობს. ტიტულის ნიშანი არ ირეცხება. თუ მანქანას მხოლოდ დღისით უყურებთ, ამას ვერ ნახავთ.",
          "الورشة تجعل سيارة مشطوبة تبدو جاهزة. الأبواب تُغلق والطلاء متطابق والإعلان يقول مالك واحد. علامة الملكية لا تُغسل. إن نظرت إلى السيارة نهاراً فقط فلن تراها.",
          "Сервіс робить списане авто закінченим на вигляд. Двері зачиняються, фарба сходиться, оголошення каже один власник. Позначка титулу не змивається. Якщо дивитися лише вдень, ви її не побачите.",
          "Сервис делает списанную машину законченной на вид. Двери закрываются, краска сходится, объявление говорит один владелец. Отметка титула не смывается. Если смотреть только днём, вы её не увидите.",
          "修理厂能把报废车弄得很完整。门能关，漆也整齐，广告写着一手车。产权上的记号洗不掉。只在白天看车，你看不到它。",
        ),
      },
    ],
  },
];
