import type { Language } from "@/lib/languages";

const LANGS = ["en", "de", "es", "fr", "sq", "pl", "ro", "bg", "ka", "ar", "uk", "ru", "zh"] as const satisfies readonly Language[];
type LStr = Record<Language, string>;
function L(...values: readonly string[]): LStr {
  const out = {} as LStr;
  LANGS.forEach((lang, i) => { out[lang] = values[i] ?? values[0] ?? ""; });
  return out;
}

type Article = {
  id: string;
  minutes: number;
  slug: LStr;
  title: LStr;
  description: LStr;
  kicker: LStr;
  sections: { h: LStr; p: LStr }[];
};

export const BLOG_MARKET: Article[] = [
  {
    id: "korea-sheet",
    minutes: 8,
    kicker: L("Korea", "Korea", "Corea", "Corée", "Koreja", "Korea", "Coreea", "Корея", "კორეა", "كوريا", "Корея", "Корея", "韩国"),
    slug: L(
      "korean-auction-sheet-before-shipping",
      "koreanischer-auktionsbogen-vor-dem-versand",
      "ficha-subasta-coreana-antes-del-envio",
      "fiche-enchere-coreenne-avant-expedition",
      "fleta-e-ankandit-korean-para-dergeses",
      "karta-aukcji-koreanskiej-przed-wysylka",
      "fisa-licitatie-coreeana-inainte-de-expediere",
      "list-koreyski-targ-predi-izprashtane",
      "koreuli-aukcionis-purceli-gagzavnamde",
      "waraqat-mazad-kuri-qabla-al-shahn",
      "koreyskyy-auktsionnyy-lyst-do-vidpravky",
      "koreyskiy-auktsionnyy-list-do-otpravki",
      "hanguo-paimai-dan-chuyun-qian",
    ),
    title: L(
      "What the Korean auction sheet says before the car is shipped",
      "Was der koreanische Auktionsbogen sagt, bevor das Auto losfährt",
      "Qué dice la ficha de subasta coreana antes de que el coche salga",
      "Ce que dit la fiche d'enchère coréenne avant le départ du bateau",
      "Çfarë thotë fleta e ankandit korean para se makina të niset",
      "Co mówi karta koreańskiej aukcji, zanim auto wypłynie",
      "Ce spune fișa de licitație coreeană înainte ca mașina să plece",
      "Какво пише в корейския тръжен лист, преди колата да тръгне",
      "რას ამბობს კორეული აუქციონის ფურცელი, სანამ მანქანა გაემგზავრება",
      "ماذا تقول ورقة المزاد الكوري قبل أن تُشحَن السيارة",
      "Що написано в корейському аукціонному листі до відправки",
      "Что написано в корейском аукционном листе до отправки",
      "韩国拍卖单在装船之前写了什么",
    ),
    description: L(
      "The advert is written after the car leaves Korea. The kilometres and the repairs were written while it was still there.",
      "Die Anzeige entsteht, nachdem das Auto Korea verlassen hat. Kilometer und Reparaturen standen schon fest, als es noch dort war.",
      "El anuncio se escribe cuando el coche ya salió de Corea. Los kilómetros y las reparaciones se anotaron mientras seguía allí.",
      "L'annonce est écrite après le départ de Corée. Les kilomètres et les réparations ont été notés tant que la voiture y était encore.",
      "Shpallja shkruhet pasi makina ka dalë nga Koreja. Kilometrat dhe riparimet janë shkruar kur ajo ishte ende atje.",
      "Ogłoszenie powstaje, gdy auto już opuściło Koreę. Kilometry i naprawy zapisano, kiedy jeszcze tam stało.",
      "Anunțul se scrie după ce mașina a plecat din Coreea. Kilometrii și reparațiile au fost notate cât era încă acolo.",
      "Обявата се пише, след като колата е напуснала Корея. Километрите и ремонтите са записани, докато още е била там.",
      "განცხადება იწერება მას შემდეგ, რაც მანქანა კორეას ტოვებს. კილომეტრები და რემონტი მაშინ ჩაიწერა, როცა ჯერ იქ იყო.",
      "الإعلان يُكتب بعد أن تغادر السيارة كوريا. الكيلومترات والتصليحات سُجّلت وهي ما زالت هناك.",
      "Оголошення пишуть після того, як авто виїхало з Кореї. Кілометри й ремонти записали, поки воно ще було там.",
      "Объявление пишут после того, как машина уехала из Кореи. Километры и ремонты записали, пока она ещё была там.",
      "广告是车离开韩国以后才写的。公里和维修是车还在那边时记下的。",
    ),
    sections: [
      {
        h: L(
          "The sheet is older than the advert",
          "Der Bogen ist älter als die Anzeige",
          "La ficha es más vieja que el anuncio",
          "La fiche est plus vieille que l'annonce",
          "Fleta është më e vjetër se shpallja",
          "Karta jest starsza niż ogłoszenie",
          "Fișa e mai veche decât anunțul",
          "Листът е по-стар от обявата",
          "ფურცელი განცხადებაზე ძველია",
          "الورقة أقدم من الإعلان",
          "Лист старший за оголошення",
          "Лист старше объявления",
          "拍卖单比广告更早",
        ),
        p: L(
          "A Hyundai or a Kia that turns up in your city usually sat in a Korean auction first. While it was still there, someone wrote the kilometres, a grade, and whether a panel had been repaired or replaced. Then it went on a ship. The seller you meet writes a shorter story: one owner, low kilometres, no accidents. That story can be true. It can also be the version that fits the asking price. Ask to see the sheet, not only the photos.",
          "Ein Hyundai oder ein Kia, der bei Ihnen ankommt, stand vorher meist auf einer koreanischen Auktion. Dort wurden Kilometer, eine Note und reparierte oder getauschte Bleche festgehalten. Danach ging das Auto aufs Schiff. Der Verkäufer hier erzählt es kürzer: ein Halter, wenig Kilometer, unfallfrei. Das kann stimmen. Es kann auch die Fassung sein, die zum Preis passt. Verlangen Sie den Bogen, nicht nur die Fotos.",
          "Un Hyundai o un Kia que aparece en tu ciudad suele haber pasado antes por una subasta en Corea. Allí anotaron los kilómetros, una nota y si un panel se reparó o se cambió. Luego subió al barco. El vendedor que conoces cuenta una historia más corta: un dueño, pocos kilómetros, sin accidentes. Puede ser cierta. También puede ser la versión que encaja con el precio. Pide la ficha, no solo las fotos.",
          "Une Hyundai ou une Kia qui arrive chez vous a souvent d'abord été en vente aux enchères en Corée. Là-bas, on a noté les kilomètres, une cote, et si un panneau avait été réparé ou changé. Ensuite le bateau. Le vendeur que vous voyez raconte plus court: un propriétaire, peu de kilomètres, pas d'accident. Cela peut être vrai. Cela peut aussi être la version qui tient dans le prix. Demandez la fiche, pas seulement les photos.",
          "Një Hyundai ose një Kia që del në qytetin tënd zakonisht ka qëndruar më parë në një ankand në Kore. Atje kanë shkruar kilometrat, një notë, dhe nëse një panel është riparuar apo ndërruar. Pastaj ka hipur në anije. Shitësi që takon e tregon më shkurt: një pronar, pak kilometra, pa aksidente. Mund të jetë e vërtetë. Mund të jetë edhe versioni që i përshtatet çmimit. Kërko fletën, jo vetëm fotot.",
          "Hyundai albo Kia, które pojawia się u ciebie, zwykle najpierw stało na koreańskiej aukcji. Tam zapisano kilometry, ocenę i to, czy blachę naprawiono albo wymieniono. Potem auto weszło na statek. Sprzedawca, którego spotykasz, opowiada krócej: jeden właściciel, mało kilometrów, bez wypadków. To może być prawda. To może też być wersja, która pasuje do ceny. Proś o kartę, nie tylko o zdjęcia.",
          "Un Hyundai sau un Kia care apare la tine a stat de obicei întâi la o licitație în Coreea. Acolo s-au notat kilometrii, o notă și dacă un panou a fost reparat sau schimbat. Apoi a urcat pe vapor. Vânzătorul pe care îl vezi spune pe scurt: un proprietar, puțini kilometri, fără accidente. Poate fi adevărat. Poate fi și varianta care încape în preț. Cere fișa, nu doar pozele.",
          "Хюндай или Киа, която се появява при вас, обикновено първо е била на търг в Корея. Там са записани километрите, оценката и дали панел е ремонтиран или сменен. После колата е качила кораб. Продавачът, когото срещате, разказва по-късо: един собственик, малко километри, без катастрофи. Може да е вярно. Може и да е версията, която пасва на цената. Искайте листа, не само снимките.",
          "ჰიუნდაი ან კია, რომელიც თქვენს ქალაქში ჩნდება, ჩვეულებრივ ჯერ კორეის აუქციონზე იდგა. იქ ჩაიწერა კილომეტრები, შეფასება და შეაკეთეს თუ შეცვალეს პანელი. მერე გემზე ავიდა. გამყიდველი, რომელსაც ხვდებით, მოკლედ ყვება: ერთი მფლობელი, ცოტა კილომეტრი, ავარიის გარეშე. შეიძლება სიმართლე იყოს. შეიძლება ის ვერსიაც იყოს, რომელიც ფასს ერგება. ფურცელი ითხოვეთ, არა მხოლოდ ფოტოები.",
          "هيونداي أو كيا تظهر في مدينتك غالباً كانت أولاً في مزاد في كوريا. هناك كتبوا الكيلومترات والتقييم وهل لوح أُصلح أو استُبدل. ثم ركبت السفينة. البائع الذي تقابله يحكي أقصر: مالك واحد، كيلومترات قليلة، بلا حوادث. قد يكون هذا صحيحاً. وقد يكون النسخة التي تناسب السعر. اطلب الورقة، لا الصور وحدها.",
          "Hyundai чи Kia, що з'являється у вашому місті, зазвичай спочатку стояла на аукціоні в Кореї. Там записали кілометри, оцінку і те, чи панель ремонтували чи міняли. Потім авто сіло на корабель. Продавець, якого ви зустрічаєте, розповідає коротше: один власник, мало кілометрів, без ДТП. Це може бути правда. Це може бути і версія, яка влізає в ціну. Просіть лист, а не лише фото.",
          "Hyundai или Kia, которая появляется у вас в городе, обычно сначала стояла на аукционе в Корее. Там записали километры, оценку и то, ремонтировали панель или меняли. Потом машина села на корабль. Продавец, которого вы встречаете, рассказывает короче: один владелец, мало километров, без ДТП. Это может быть правда. Это может быть и версия, которая укладывается в цену. Просите лист, а не только фото.",
          "一辆现代或起亚出现在你城里，多半先在韩国拍过。人还在韩国的时候，就把公里、评分、哪块板修过或换过写下来了。然后车上了船。你见到的卖家说得更短：一个车主，公里少，没出过事。这可能是真的。也可能只是刚好配得上那个价。要那张单，别只要照片。",
        ),
      },
      {
        h: L(
          "A good grade still has small print",
          "Eine gute Note hat Kleingedrucktes",
          "Una buena nota igual tiene letra pequeña",
          "Une bonne cote a quand même des petites lignes",
          "Një notë e mirë ka prapë shkrim të imët",
          "Dobra ocena i tak ma drobny druk",
          "O notă bună tot are literă mică",
          "Добрата оценка пак има ситен шрифт",
          "კარგ შეფასებას წვრილი ასოც აქვს",
          "التقييم الجيد فيه سطور صغيرة",
          "Добра оцінка все одно має дрібний шрифт",
          "Хорошая оценка всё равно с мелким шрифтом",
          "评分好看，下面还有小字",
        ),
        p: L(
          "The letter or number on the sheet is only a summary. Under it you often find exchange, repair, or paint. A high grade with those words is not the same car as a high grade without them. Pay for the repair, not for the letter. If the seller will not show the sheet, you are paying for the advert.",
          "Der Buchstabe oder die Zahl auf dem Bogen ist nur eine Zusammenfassung. Darunter stehen oft Tausch, Reparatur oder Lack. Eine hohe Note mit diesen Wörtern ist nicht dasselbe Auto wie eine hohe Note ohne sie. Zahlen Sie die Reparatur, nicht den Buchstaben. Wer den Bogen nicht zeigt, verkauft Ihnen die Anzeige.",
          "La letra o el número de la ficha es solo un resumen. Debajo suelen aparecer cambio, reparación o pintura. Una nota alta con esas palabras no es el mismo coche que una nota alta sin ellas. Paga la reparación, no la letra. Si el vendedor no enseña la ficha, estás pagando el anuncio.",
          "La lettre ou le chiffre sur la fiche n'est qu'un résumé. En dessous on trouve souvent échange, réparation ou peinture. Une bonne cote avec ces mots n'est pas la même voiture qu'une bonne cote sans eux. Payez la réparation, pas la lettre. Si le vendeur ne montre pas la fiche, vous payez l'annonce.",
          "Shkronja ose numri në fletë është vetëm përmbledhje. Poshtë shpesh shkruan ndërrim, riparim ose bojë. Një notë e lartë me këto fjalë nuk është e njëjta makinë si një notë e lartë pa to. Paguaj riparimin, jo shkronjën. Nëse shitësi nuk ta tregon fletën, po paguan shpalljen.",
          "Litera albo cyfra na karcie to tylko skrót. Pod spodem często jest wymiana, naprawa albo lakier. Wysoka ocena z tymi słowami to nie to samo auto co wysoka ocena bez nich. Płać za naprawę, nie za literę. Jak sprzedawca nie pokaże karty, płacisz za ogłoszenie.",
          "Litera sau cifra de pe fișă e doar un rezumat. Sub ea apare des schimb, reparație sau vopsea. O notă mare cu aceste cuvinte nu e aceeași mașină ca o notă mare fără ele. Plătești reparația, nu litera. Dacă vânzătorul nu arată fișa, plătești anunțul.",
          "Буквата или цифрата на листа е само обобщение. Под нея често пише смяна, ремонт или боя. Висока оценка с тези думи не е същата кола като висока оценка без тях. Плащате ремонта, не буквата. Ако продавачът не покаже листа, плащате обявата.",
          "ასო ან რიცხვი ფურცელზე მხოლოდ მოკლე ჯამია. ქვემოთ ხშირად წერია შეცვლა, შეკეთება ან საღებავი. მაღალი შეფასება ამ სიტყვებით არ არის იგივე მანქანა, რაც მაღალი შეფასება მათ გარეშე. რემონტს იხდით, ასოს კი არა. თუ გამყიდველი ფურცელს არ გიჩვენებთ, განცხადებას იხდით.",
          "الحرف أو الرقم على الورقة مجرد ملخص. تحته كثيراً ما تجد استبدال أو تصليح أو طلاء. تقييم عالٍ مع هذه الكلمات ليس السيارة نفسها كتقييم عالٍ من دونها. ادفع ثمن التصليح، لا الحرف. إن لم يُظهر البائع الورقة فأنت تدفع ثمن الإعلان.",
          "Літера чи цифра на листі це лише короткий підсумок. Під нею часто стоїть заміна, ремонт або фарба. Висока оцінка з цими словами це не те саме авто, що висока оцінка без них. Платіть за ремонт, не за літеру. Якщо продавець не покаже лист, ви платите за оголошення.",
          "Буква или цифра на листе это только короткое резюме. Под ней часто стоит замена, ремонт или краска. Высокая оценка с этими словами это не та же машина, что высокая оценка без них. Платите за ремонт, не за букву. Если продавец не покажет лист, вы платите за объявление.",
          "单子上的字母或数字只是一个总评。下面常常写着更换、维修、喷漆。评分高、底下却有这些字，和评分高、底下没有这些字，不是同一辆车。你买的是维修，不是那个字母。卖家不肯出示单子，你付的就是广告的钱。",
        ),
      },
      {
        h: L(
          "Forty thousand kilometres needs a reason",
          "Vierzigtausend Kilometer brauchen einen Grund",
          "Cuarenta mil kilómetros necesitan un motivo",
          "Quarante mille kilomètres demandent une raison",
          "Dyzet mijë kilometra duan një arsye",
          "Czterdzieści tysięcy kilometrów chce powodu",
          "Patruzeci de mii de kilometri cer un motiv",
          "Четиридесет хиляди километра искат причина",
          "ორმოცი ათასი კილომეტრი მიზეზს ითხოვს",
          "أربعون ألف كيلومتر تحتاج سبباً",
          "Сорок тисяч кілометрів потребують причини",
          "Сорок тысяч километров требуют причины",
          "四万公里得有个理由",
        ),
        p: L(
          "A 2017 Tucson at 40,000 km can be a car that barely left the city. It can also be a cluster that was opened before export. Look at the driver's seat, the shine worn off the wheel, and the week and year stamped on the tyres. If the sheet says 160,000 and the dash says 50,000, talk money from the sheet. The number on the dash is the easy one to change.",
          "Ein Tucson von 2017 mit 40.000 km kann ein Stadtauto sein, das kaum rauskam. Es kann auch ein Tacho sein, der vor dem Export geöffnet wurde. Schauen Sie auf den Fahrersitz, die blanke Stelle am Lenkrad und die Woche und das Jahr auf den Reifen. Stehen auf dem Bogen 160.000 und im Cockpit 50.000, verhandeln Sie mit dem Bogen. Die Zahl am Tacho ist die, die sich leicht ändern lässt.",
          "Un Tucson de 2017 con 40.000 km puede ser un coche de ciudad que casi no salió. También puede ser un cuadro abierto antes de exportar. Mira el asiento del conductor, el desgaste del volante y la semana y el año marcados en los neumáticos. Si la ficha dice 160.000 y el tablero 50.000, negocia con la ficha. El número del tablero es el fácil de cambiar.",
          "Un Tucson 2017 à 40 000 km peut être une voiture de ville qui est à peine sortie. Ce peut aussi être un compteur ouvert avant l'export. Regardez le siège conducteur, le volant lisse et la semaine et l'année sur les pneus. Si la fiche dit 160 000 et le tableau 50 000, négociez avec la fiche. Le chiffre du tableau est le plus simple à changer.",
          "Një Tucson 2017 me 40.000 km mund të jetë makinë qyteti që mezi ka dalë. Mund të jetë edhe një panel që është hapur para eksportit. Shiko sediljen e shoferit, shkëlqimin e fshirë te timoni, dhe javën me vitin mbi goma. Nëse fleta thotë 160.000 dhe paneli 50.000, bisedo me fletën. Shifra e panelit është ajo që ndryshohet lehtë.",
          "Tucson z 2017 i 40 000 km może być autem miejskim, które prawie nie wyjeżdżało. Może też być licznikiem otwartym przed eksportem. Patrz na fotel kierowcy, wytarty błysk na kierownicy i tydzień z rokiem na oponach. Jeśli karta mówi 160 000, a licznik 50 000, rozmawiaj o pieniądzach z kartą. Cyfra na liczniku najłatwiej się zmienia.",
          "Un Tucson din 2017 cu 40.000 km poate fi o mașină de oraș care abia a ieșit. Poate fi și un bord deschis înainte de export. Uită-te la scaunul șoferului, la luciul tocit de pe volan și la săptămâna și anul de pe anvelope. Dacă fișa spune 160.000 și bordul 50.000, negociază cu fișa. Cifra de pe bord e cea ușor de schimbat.",
          "Тусон от 2017 с 40 000 км може да е градска кола, която почти не е излизала. Може и да е табло, отворено преди износа. Гледайте седалката на шофьора, изтрития блясък на волана и седмицата и годината върху гумите. Ако листът казва 160 000, а таблото 50 000, преговаряйте с листа. Цифрата на таблото се сменя лесно.",
          "2017 წლის Tucson 40 000 კმ-ით შეიძლება ქალაქის მანქანა იყოს, რომელიც თითქმის არ გასულა. შეიძლება პანელიც იყოს, რომელიც ექსპორტამდე გახსნეს. ნახეთ მძღოლის სავარძელი, საჭეზე წაშლილი ბზინვარება და საბურავზე კვირა და წელი. თუ ფურცელი 160 000-ს ამბობს, დაფა კი 50 000-ს, ფულზე ფურცლით ილაპარაკეთ. დაფის ციფრი ადვილად იცვლება.",
          "توسان 2017 بـ 40 ألف كم قد تكون سيارة مدينة بالكاد خرجت. وقد تكون عداداً فُتح قبل التصدير. انظر مقعد السائق، لمعان المقود الممسح، والأسبوع والسنة على الإطارات. إن قالت الورقة 160 ألفاً والعداد 50 ألفاً، تفاوض بالورقة. رقم العداد هو الأسهل تغييراً.",
          "Tucson 2017 року з 40 000 км може бути міським авто, яке майже не виїжджало. Може бути і панеллю, яку відкрили перед експортом. Дивіться на сидіння водія, стертий блиск на кермі і тиждень з роком на шинах. Якщо лист каже 160 000, а панель 50 000, торгуйтеся з листа. Цифру на панелі змінити найлегше.",
          "Tucson 2017 года с 40 000 км может быть городской машиной, которая почти не выезжала. Может быть и панелью, которую вскрыли перед экспортом. Смотрите на сиденье водителя, стёртый блеск на руле и неделю с годом на шинах. Если лист говорит 160 000, а панель 50 000, торгуйтесь по листу. Цифру на панели изменить легче всего.",
          "一辆 2017 年的途胜显示 4 万公里，可能真是几乎不出城的车。也可能是出口前把仪表拆开改过。看驾驶座、方向盘磨掉的光、轮胎上的周次和年份。单子写 16 万，表上写 5 万，就按单子谈价。表上的数字最好改。",
        ),
      },
      {
        h: L(
          "Do not pay to hold a car that is still at sea",
          "Zahlen Sie nicht, um ein Auto auf See festzuhalten",
          "No pagues por reservar un coche que sigue en el mar",
          "Ne payez pas pour bloquer une voiture encore en mer",
          "Mos paguaj për të mbajtur një makinë që është ende në det",
          "Nie płać, żeby trzymać auto, które jest jeszcze na morzu",
          "Nu plăti ca să ții o mașină care e încă pe mare",
          "Не плащайте, за да задържите кола, която още е в морето",
          "ნუ გადაიხდით, რომ ზღვაზე მყოფი მანქანა დაგიჭიროთ",
          "لا تدفع لتحجز سيارة ما زالت في البحر",
          "Не платіть, щоб утримати авто, яке ще в морі",
          "Не платите, чтобы удержать машину, которая ещё в море",
          "车还在海上，别先交钱占着",
        ),
        p: L(
          "The rush is part of the sale. The slot is taken, the ship leaves tomorrow, another buyer is waiting. None of that is a reason to send money before you have the 17 characters of the VIN and a report that matches the photos. A real car is still there after you check it. A story is not.",
          "Die Eile gehört zum Verkauf. Der Platz ist weg, das Schiff fährt morgen, der nächste Käufer wartet. Nichts davon ist ein Grund, Geld zu schicken, bevor Sie die 17 Zeichen der VIN haben und einen Bericht, der zu den Fotos passt. Ein echtes Auto ist nach der Prüfung noch da. Eine Geschichte nicht.",
          "La prisa forma parte de la venta. El cupo está cogido, el barco sale mañana, otro comprador espera. Nada de eso es motivo para enviar dinero antes de tener los 17 caracteres del VIN y un informe que coincida con las fotos. Un coche de verdad sigue ahí después de comprobarlo. Una historia no.",
          "La précipitation fait partie de la vente. La place est prise, le bateau part demain, un autre acheteur attend. Rien de cela n'est une raison d'envoyer de l'argent avant d'avoir les 17 caractères du VIN et un rapport qui correspond aux photos. Une vraie voiture est encore là après le contrôle. Une histoire, non.",
          "Nxitimi është pjesë e shitjes. Vendi është zënë, anija niset nesër, një blerës tjetër pret. Asnjë nga këto nuk është arsye të dërgosh para para se të kesh 17 shenjat e VIN-it dhe një raport që përputhet me fotot. Një makinë e vërtetë është ende aty pasi e kontrollon. Një rrëfim jo.",
          "Pośpiech jest częścią sprzedaży. Miejsce zajęte, statek płynie jutro, czeka kolejny kupujący. Nic z tego nie jest powodem, żeby wysłać pieniądze, zanim masz 17 znaków VIN i raport zgodny ze zdjęciami. Prawdziwe auto jest jeszcze na miejscu po sprawdzeniu. Opowieść nie.",
          "Graba face parte din vânzare. Locul e luat, vaporul pleacă mâine, alt cumpărător așteaptă. Nimic din astea nu e motiv să trimiți bani înainte să ai cele 17 caractere ale VIN-ului și un raport care se potrivește cu pozele. O mașină adevărată e încă acolo după ce o verifici. O poveste nu.",
          "Бързането е част от продажбата. Мястото е заето, корабът тръгва утре, чака друг купувач. Нищо от това не е причина да пратите пари, преди да имате 17-те знака на VIN и отчет, който съвпада със снимките. Истинска кола е още там след проверката. Историята не.",
          "აჩქარება გაყიდვის ნაწილია. ადგილი დაკავებულია, გემი ხვალ მიდის, სხვა მყიდველი ელოდება. არცერთი ამათგანი არ არის საბაბი, ფული გაგზავნოთ, სანამ VIN-ის 17 ნიშანი და ფოტოებთან დამთხვეული ანგარიში არ გაქვთ. ნამდვილი მანქანა შემოწმების შემდეგაც იქ არის. ამბავი კი არა.",
          "الاستعجال جزء من البيع. المكان محجوز، السفينة تبحر غداً، مشترٍ آخر ينتظر. لا شيء من هذا سبب لإرسال مال قبل أن تملك أحرف الهيكل السبعة عشر وتقريراً يطابق الصور. السيارة الحقيقية ما زالت هناك بعد الفحص. الحكاية لا.",
          "Поспіх це частина продажу. Місце зайняте, корабель іде завтра, чекає інший покупець. Ніщо з цього не причина надсилати гроші, поки немає 17 знаків VIN і звіту, який збігається з фото. Справжнє авто після перевірки ще на місці. Історія ні.",
          "Спешка это часть продажи. Место занято, корабль уходит завтра, ждёт другой покупатель. Ничто из этого не повод отправлять деньги, пока нет 17 знаков VIN и отчёта, который совпадает с фото. Настоящая машина после проверки ещё на месте. История нет.",
          "催你是这门买卖的一部分。舱位占了，船明天开，下一位买家在等。这些都不是理由，让你在拿到 17 位 VIN、并且报告和照片对得上之前就把钱打过去。真车查完还在。故事不会。",
        ),
      },
    ],
  },
  {
    id: "odo-scam",
    minutes: 8,
    kicker: L("Mileage", "Kilometer", "Kilómetros", "Kilométrage", "Kilometrat", "Przebieg", "Kilometri", "Пробег", "კილომეტრები", "الكيلومترات", "Пробіг", "Пробег", "公里"),
    slug: L(
      "how-a-rolled-back-odometer-is-sold",
      "wie-ein-zurueckgestellter-tacho-verkauft-wird",
      "como-te-venden-un-cuentakilometros-atrasado",
      "comment-on-vous-vend-un-compteur-recule",
      "si-shitet-nje-kilometrazh-i-kthyer",
      "jak-sprzedaja-cofniety-licznik",
      "cum-ti-se-vinde-un-kilometraj-dat-inapoi",
      "kak-prodavat-vurnat-kilometrazh",
      "rogor-yidiba-dabruneuli-kilometrebi",
      "kayfa-yubaa-adad-muraja",
      "yak-prodayut-vidmotanyy-probig",
      "kak-prodayut-sknochennyy-probeg",
      "lichen-shi-zenme-mai-chuqu-de",
    ),
    title: L(
      "The odometer was rolled back. The car was not.",
      "Der Tacho wurde zurückgestellt. Das Auto nicht.",
      "El cuentakilómetros se atrasó. El coche no.",
      "Le compteur a été reculé. La voiture, non.",
      "Kilometrat janë kthyer. Makina jo.",
      "Licznik cofnięto. Auta nie.",
      "Kilometrajul a fost dat înapoi. Mașina nu.",
      "Километражът е върнат. Колата не.",
      "კილომეტრები დააბრუნეს. მანქანა არა.",
      "العادّ أُرجع. السيارة لا.",
      "Пробіг відмотали. Авто ні.",
      "Пробег скрутили. Машину нет.",
      "公里被回了。车没有。",
    ),
    description: L(
      "A low number on the dash is the cheapest part of a used-car lie. The seat, the tyres and the old records are harder to edit.",
      "Eine niedrige Zahl im Cockpit ist der billigste Teil einer Lüge beim Gebrauchten. Sitz, Reifen und alte Akten lassen sich schlechter ändern.",
      "Un número bajo en el tablero es la parte más barata de la mentira. El asiento, los neumáticos y los registros viejos cuestan más de retocar.",
      "Un petit chiffre au tableau est la part la moins chère du mensonge. Le siège, les pneus et les vieux dossiers sont plus durs à retoucher.",
      "Një shifër e ulët në panel është pjesa më e lirë e gënjeshtrës. Sedilja, gomat dhe regjistrat e vjetër ndryshohen më vështirë.",
      "Niska liczba na liczniku to najtańsza część kłamstwa. Fotel, opony i stare zapisy trudniej podrobić.",
      "O cifră mică pe bord e partea cea mai ieftină a minciunii. Scaunul, anvelopele și evidențele vechi se schimbă mai greu.",
      "Ниска цифра на таблото е най-евтината част от лъжата. Седалката, гумите и старите записи се пипат по-трудно.",
      "დაბალი ციფრი დაფაზე ტყუილის ყველაზე იაფი ნაწილია. სავარძელი, საბურავები და ძველი ჩანაწერები უფრო ძნელად იცვლება.",
      "رقم منخفض على العداد هو أرخص جزء من الكذبة. المقعد والإطارات والسجلات القديمة أصعب تعديلاً.",
      "Мала цифра на панелі це найдешевша частина брехні. Сидіння, шини й старі записи змінити важче.",
      "Малая цифра на панели это самая дешёвая часть лжи. Сиденье, шины и старые записи менять труднее.",
      "表上的小数字是这套谎里最便宜的部分。座椅、轮胎和旧记录更难改。",
    ),
    sections: [
      {
        h: L(
          "They sell the number, not the distance",
          "Verkauft wird die Zahl, nicht die Strecke",
          "Venden el número, no la distancia",
          "On vend le chiffre, pas la distance",
          "Shesin shifrën, jo rrugën",
          "Sprzedają liczbę, nie dystans",
          "Vând cifra, nu distanța",
          "Продават цифрата, не разстоянието",
          "ციფრს ყიდიან, არა გზას",
          "يبيعون الرقم لا المسافة",
          "Продають цифру, не відстань",
          "Продают цифру, не расстояние",
          "卖的是数字，不是跑过的路",
        ),
        p: L(
          "Rolling a cluster back, or fitting a cleaner one, takes an afternoon. The rest of the car keeps the kilometres it already did. That is why a 90,000 km listing can still have a sagging driver's bolster, a polished wheel and tyres whose date code is six years old. The advert is written from the cluster. The car is not.",
          "Einen Tacho zurückzustellen oder ein saubereres Kombiinstrument einzubauen dauert einen Nachmittag. Der Rest des Autos behält die Kilometer, die es schon gefahren ist. Deshalb kann ein Inserat mit 90.000 km trotzdem eine durchgesessene Fahrerseite, ein blankes Lenkrad und Reifen mit sechs Jahre altem Datum haben. Die Anzeige folgt dem Tacho. Das Auto nicht.",
          "Atrasar un cuadro, o poner uno más limpio, lleva una tarde. El resto del coche se queda con los kilómetros que ya hizo. Por eso un anuncio de 90.000 km puede tener el asiento del conductor hundido, el volante pulido y neumáticos con fecha de hace seis años. El anuncio sale del cuadro. El coche no.",
          "Reculer un compteur, ou en poser un plus propre, prend un après-midi. Le reste de la voiture garde les kilomètres déjà faits. C'est pour cela qu'une annonce à 90 000 km peut avoir un siège conducteur affaissé, un volant lisse et des pneus datés de six ans. L'annonce vient du compteur. La voiture, non.",
          "Ta kthesh panelin, ose të vësh një më të pastër, të merr një pasdite. Pjesa tjetër e makinës i mban kilometrat që i ka bërë. Prandaj një shpallje me 90.000 km mund të ketë sedilje shoferi të ulur, timon të shndritshëm dhe goma me datë gjashtëvjeçare. Shpallja del nga paneli. Makina jo.",
          "Cofnięcie licznika albo włożenie czystszego zajmuje popołudnie. Reszta auta zostaje z kilometrami, które już przejechało. Dlatego ogłoszenie na 90 000 km może mieć zapadnięty fotel, wypolerowaną kierownicę i opony z datą sprzed sześciu lat. Ogłoszenie jest z licznika. Auto nie.",
          "Dai kilometrajul înapoi, sau pui un bord mai curat, îți ia o după-amiază. Restul mașinii rămâne cu kilometrii deja făcuți. De aia un anunț cu 90.000 km poate avea scaunul șoferului lăsat, volanul lucios și anvelope datate de șase ani. Anunțul vine din bord. Mașina nu.",
          "Да върнеш таблото, или да сложиш по-чисто, отнема следобед. Останалото от колата пази километрите, които вече е изминала. Затова обява с 90 000 км може да има хлътнала шофьорска седалка, излъскан волан и гуми с дата отпреди шест години. Обявата идва от таблото. Колата не.",
          "კილომეტრების დაბრუნება ან უფრო სუფთა პანელის დაყენება ნახევარ დღეს იღებს. მანქანის დანარჩენი ნაწილი იმ კილომეტრებს ინახავს, რაც უკვე გაიარა. ამიტომ 90 000 კმ-იან განცხადებას შეიძლება ჩაჯდომილი სავარძელი, გაპრიალებული საჭე და ექვსი წლის საბურავი ჰქონდეს. განცხადება პანელიდან მოდის. მანქანა არა.",
          "إرجاع العداد أو تركيب آخر أنظف يأخذ فترة بعد الظهر. بقية السيارة تُبقي الكيلومترات التي قطعتها. لذلك إعلان بـ 90 ألف كم قد يكون فيه مقعد سائق هابط ومقود لامع وإطارات تاريخها ست سنوات. الإعلان من العداد. السيارة لا.",
          "Відмотати пробіг або поставити чистішу панель займає половину дня. Решта авто лишається з кілометрами, які воно вже проїхало. Тому оголошення на 90 000 км може мати просиджене сидіння, відполіроване кермо і шини з датою шість років тому. Оголошення з панелі. Авто ні.",
          "Скрутить пробег или поставить панель почище занимает полдня. Остальная машина остаётся с километрами, которые она уже проехала. Поэтому объявление на 90 000 км может иметь просиженное сиденье, отполированный руль и шины с датой шесть лет назад. Объявление с панели. Машина нет.",
          "把里程回掉，或者换一块更干净的仪表，一个下午就够。车身上已经跑过的路还在。所以标着 9 万公里的广告，仍可能有塌了的驾驶座、磨亮的方向盘、胎侧日期是六年前。广告跟着表走。车不跟着。",
        ),
      },
      {
        h: L(
          "Service books get rewritten too",
          "Auch Servicehefte werden umgeschrieben",
          "El libro de revisiones también se reescribe",
          "Le carnet d'entretien se réécrit aussi",
          "Edhe libri i servisit rishkruhet",
          "Książkę serwisową też się przepisuje",
          "Și cartea de service se rescrie",
          "Сервизната книжка също се пренаписва",
          "სერვისის წიგნიც ხელახლა იწერება",
          "دفتر الصيانة يُعاد كتابته أيضاً",
          "Сервісну книжку теж переписують",
          "Сервисную книжку тоже переписывают",
          "保养本也会重写",
        ),
        p: L(
          "A stamped booklet that jumps from 40,000 to 70,000 and then lands on 62,000 is not a history. Stamps are cheap. What is harder to fake is a workshop invoice with a VIN, a date and a kilometre reading that is higher than the dash today. One old invoice beats a neat booklet.",
          "Ein gestempeltes Heft, das von 40.000 auf 70.000 springt und dann bei 62.000 landet, ist keine Historie. Stempel sind billig. Schwerer zu fälschen ist eine Werkstattrechnung mit VIN, Datum und einem Kilometerstand, der höher liegt als der Tacho heute. Eine alte Rechnung sagt mehr als ein ordentliches Heft.",
          "Un libro sellado que salta de 40.000 a 70.000 y luego cae en 62.000 no es un historial. Los sellos son baratos. Lo difícil de falsificar es una factura de taller con VIN, fecha y un kilometraje más alto que el tablero de hoy. Una factura vieja dice más que un libro bonito.",
          "Un carnet tamponné qui passe de 40 000 à 70 000 puis retombe à 62 000 n'est pas un historique. Les tampons sont bon marché. Plus dur à fabriquer: une facture d'atelier avec le VIN, une date et un kilométrage plus haut que le tableau aujourd'hui. Une vieille facture en dit plus qu'un carnet bien tenu.",
          "Një libër i vulosur që kalon nga 40.000 në 70.000 dhe pastaj bie te 62.000 nuk është histori. Vulësat janë të lira. Më vështirë falsifikohet një faturë servisi me VIN, datë dhe kilometrazh më të lartë se paneli sot. Një faturë e vjetër ia kalon një libri të pastër.",
          "Podstemplowana książka, która skacze z 40 000 na 70 000 i ląduje na 62 000, nie jest historią. Pieczątki są tanie. Trudniej podrobić fakturę warsztatu z VIN, datą i przebiegiem wyższym niż licznik dzisiaj. Jedna stara faktura mówi więcej niż ładna książka.",
          "O carte ștampilată care sare de la 40.000 la 70.000 și apoi cade la 62.000 nu e un istoric. Ștampilele sunt ieftine. Mai greu de fals e o factură de service cu VIN, dată și un kilometraj mai mare decât bordul de azi. O factură veche spune mai mult decât o carte îngrijită.",
          "Книжка с печати, която скача от 40 000 на 70 000 и после пада на 62 000, не е история. Печатите са евтини. По-трудно се фалшифицира фактура от сервиз с VIN, дата и километраж по-висок от таблото днес. Една стара фактура казва повече от спретната книжка.",
          "დასმული წიგნი, რომელიც 40 000-დან 70 000-ზე ხტება და მერე 62 000-ზე ეშვება, ისტორია არ არის. შტამპი იაფია. უფრო ძნელია სერვისის ანგარიშის გაყალბება VIN-ით, თარიღით და კილომეტრაჟით, რომელიც დღევანდელ დაფაზე მაღალია. ერთი ძველი ანგარიში მოწესრიგებულ წიგნს სჯობნის.",
          "دفتر مختوم يقفز من 40 ألفاً إلى 70 ألفاً ثم يهبط إلى 62 ألفاً ليس تاريخاً. الأختام رخيصة. الأصعب تزوير فاتورة ورشة فيها رقم الهيكل وتاريخ وقراءة أعلى من العداد اليوم. فاتورة قديمة أوضح من دفتر مرتب.",
          "Книжка з печатками, яка стрибає з 40 000 на 70 000 і потім сідає на 62 000, це не історія. Печатки дешеві. Важче підробити рахунок сервісу з VIN, датою і пробігом вищим, ніж панель сьогодні. Один старий рахунок каже більше за охайну книжку.",
          "Книжка с печатями, которая прыгает с 40 000 на 70 000 и потом садится на 62 000, это не история. Печати дешёвые. Труднее подделать счёт сервиса с VIN, датой и пробегом выше, чем панель сегодня. Один старый счёт говорит больше, чем аккуратная книжка.",
          "一本盖了章的本子，从 4 万跳到 7 万，再落到 6.2 万，这不是历史。章不贵。难造的是一张修理厂发票：有车架号、日期，而且当时的公里比今天表上还高。一张旧发票胜过一本整齐的本子。",
        ),
      },
      {
        h: L(
          "Auction photos do not move with the cluster",
          "Auktionsfotos ziehen nicht mit dem Tacho um",
          "Las fotos de subasta no se van con el cuadro",
          "Les photos d'enchère ne suivent pas le compteur",
          "Fotot e ankandit nuk ikin me panelin",
          "Zdjęcia z aukcji nie przenoszą się z licznikiem",
          "Pozele de licitație nu pleacă odată cu bordul",
          "Тръжните снимки не тръгват с таблото",
          "აუქციონის ფოტოები პანელს არ მიჰყვება",
          "صور المزاد لا تنتقل مع العداد",
          "Аукціонні фото не їдуть разом із панеллю",
          "Аукционные фото не едут вместе с панелью",
          "拍卖照片不会跟着仪表走",
        ),
        p: L(
          "Insurance and dealer auctions photograph the dash on the day they sell the car. That reading stays in the file after the cluster is swapped in a workshop on the coast. Put the two numbers next to each other before you argue about price. If they disagree, the newer and prettier number is the one that was edited.",
          "Versicherungs- und Händlerauktionen fotografieren den Tacho am Verkaufstag. Die Ablesung bleibt in der Akte, auch wenn das Kombiinstrument später in einer Werkstatt an der Küste getauscht wird. Legen Sie beide Zahlen nebeneinander, bevor Sie über den Preis streiten. Wenn sie auseinanderliegen, ist die neuere und schönere die bearbeitete.",
          "Las subastas de seguros y de concesionarios fotografían el tablero el día de la venta. Esa lectura se queda en el archivo aunque luego cambien el cuadro en un taller de la costa. Pon los dos números juntos antes de discutir el precio. Si no coinciden, el más nuevo y bonito es el editado.",
          "Les enchères d'assurance et de marchands photographient le tableau le jour de la vente. Ce relevé reste dans le dossier même si le compteur est changé plus tard dans un atelier du port. Mettez les deux chiffres côte à côte avant de discuter le prix. S'ils divergent, le plus récent et le plus joli est celui qu'on a retouché.",
          "Ankandet e sigurimit dhe të tregtarëve e fotografjnë panelin ditën që shesin makinën. Ai lexim mbetet te raporti edhe pasi paneli ndërrohet te një servis bregdetar. Vëri dy shifrat pranë njëra-tjetrës para se të debatosh çmimin. Nëse nuk përputhen, shifra më e re dhe më e bukur është ajo që është ndryshuar.",
          "Aukcje ubezpieczeniowe i dealerskie fotografują licznik w dniu sprzedaży. Ten odczyt zostaje w aktach, nawet gdy licznik później wymienia warsztat przy porcie. Połóż obie liczby obok siebie, zanim zaczniesz się spierać o cenę. Jak się nie zgadzają, nowsza i ładniejsza jest tą poprawioną.",
          "Licitațiile de asigurări și ale dealerilor fotografiază bordul în ziua vânzării. Citirea rămâne în dosar chiar dacă bordul e schimbat mai târziu într-un service de pe coastă. Pune cele două cifre una lângă alta înainte să te cerți pe preț. Dacă nu se potrivesc, cifra mai nouă și mai frumoasă e cea editată.",
          "Търговете на застрахователи и търговци снимат таблото в деня на продажбата. Това отчитане остава във файла, дори таблото после да се смени в сервиз на брега. Сложете двете цифри една до друга, преди да спорите за цената. Ако не съвпадат, по-новата и по-хубавата е пипаната.",
          "სადაზღვევო და დილერული აუქციონები დაფას ყიდვის დღეს იღებენ. ეს ჩვენება საქმეში რჩება მაშინაც, როცა პანელს მერე სანაპიროს სერვისში ცვლიან. ორი ციფრი გვერდიგვერდ დააყენეთ, სანამ ფასზე იჩხუბებთ. თუ არ ემთხვევა, უფრო ახალი და ლამაზი არის შეცვლილი.",
          "مزادات التأمين والتجار تصوّر العداد يوم البيع. تلك القراءة تبقى في الملف حتى لو استُبدل العداد لاحقاً في ورشة على الساحل. ضع الرقمين جنباً إلى جنب قبل أن تجادل في السعر. إن اختلفا فالرقم الأحدث والأجمل هو المُعدَّل.",
          "Аукціони страховиків і дилерів фотографують панель у день продажу. Цей показник лишається в справі, навіть якщо панель потім міняють у сервісі на узбережжі. Покладіть дві цифри поруч, перш ніж сперечатися про ціну. Якщо вони не сходяться, новіша й гарніша це та, яку змінили.",
          "Аукционы страховщиков и дилеров фотографируют панель в день продажи. Этот показатель остаётся в деле, даже если панель потом меняют в сервисе на побережье. Положите две цифры рядом, прежде чем спорить о цене. Если они не сходятся, более новая и красивая это та, которую изменили.",
          "保险公司和车商的拍卖会在卖车当天给仪表拍照。这块表后来在海边的修理厂换掉了，那天的读数还在档案里。谈价之前把两个数字放在一起。对不上的时候，更新、更好看的那个，就是被改过的。",
        ),
      },
      {
        h: L(
          "One mismatch is enough to walk",
          "Eine Abweichung reicht zum Gehen",
          "Una diferencia basta para irte",
          "Un écart suffit pour partir",
          "Një mospërputhje mjafton për t'u larguar",
          "Jedna różnica wystarczy, żeby odejść",
          "O nepotrivire ajunge ca să pleci",
          "Едно разминаване стига, за да си тръгнете",
          "ერთი შეუსაბამობა საკმარისია, რომ წახვიდეთ",
          "اختلاف واحد يكفي للمغادرة",
          "Однієї розбіжності досить, щоб піти",
          "Одного расхождения достаточно, чтобы уйти",
          "对不上一次，就可以走",
        ),
        p: L(
          "You do not need five proofs. The dash says 48,000, the auction file says 141,000, and the driver's seat looks like the higher number. That is the car. Ask the seller to explain it before any deposit. If the answer is a story about a replaced screen and a grandmother who only drove to church, you already have your decision.",
          "Sie brauchen keine fünf Beweise. Der Tacho sagt 48.000, die Auktionsakte 141.000, und der Fahrersitz sieht nach der höheren Zahl aus. Das ist das Auto. Lassen Sie sich das erklären, bevor Geld fließt. Kommt dann eine Geschichte vom getauschten Display und der Großmutter, die nur zur Kirche fuhr, ist die Entscheidung schon da.",
          "No hacen falta cinco pruebas. El tablero dice 48.000, el archivo de subasta 141.000, y el asiento del conductor tiene pinta del número alto. Ese es el coche. Pide la explicación antes de cualquier señal. Si la respuesta es una pantalla cambiada y una abuela que solo iba a misa, ya tienes la decisión.",
          "Cinq preuves ne sont pas utiles. Le tableau dit 48 000, le dossier d'enchère 141 000, et le siège conducteur ressemble au chiffre haut. Voilà la voiture. Demandez l'explication avant tout arrhes. Si la réponse est un écran changé et une grand-mère qui n'allait qu'à l'église, la décision est déjà prise.",
          "Nuk të duhen pesë prova. Paneli tregon 48.000, fleta e ankandit 141.000, dhe sedilja e shoferit duket si shifra e lartë. Kjo është makina. Kërko shpjegimin para se të japësh kapar. Nëse përgjigjja është një ekran i ndërruar dhe një gjyshe që shkonte vetëm në kishë, vendimin e ke tashmë.",
          "Nie potrzebujesz pięciu dowodów. Licznik mówi 48 000, akta aukcji 141 000, a fotel kierowcy wygląda na wyższą liczbę. To jest to auto. Poproś o wyjaśnienie przed jakimkolwiek zadatkiem. Jeśli odpowiedź to wymieniony ekran i babcia, która jeździła tylko do kościoła, decyzję już masz.",
          "Nu-ți trebuie cinci dovezi. Bordul spune 48.000, dosarul de licitație 141.000, iar scaunul șoferului arată ca cifra mare. Asta e mașina. Cere explicația înainte de orice avans. Dacă răspunsul e un ecran schimbat și o bunică care mergea doar la biserică, decizia o ai.",
          "Не ви трябват пет доказателства. Таблото казва 48 000, тръжният файл 141 000, а шофьорската седалка изглежда като високата цифра. Това е колата. Поискайте обяснение преди всяко капаро. Ако отговорът е сменен екран и баба, която карала само до църква, решението вече е ваше.",
          "ხუთი მტკიცებულება არ გჭირდებათ. დაფა 48 000-ს ამბობს, აუქციონის საქმე 141 000-ს, მძღოლის სავარძელი კი მაღალ ციფრს ჰგავს. ეს არის მანქანა. ახსნა ითხოვეთ ნებისმიერ ავანსამდე. თუ პასუხი შეცვლილი ეკრანი და ბებიაა, რომელიც მხოლოდ ეკლესიაში დადიოდა, გადაწყვეტილება უკვე გაქვთ.",
          "لا تحتاج خمس أدلة. العداد يقول 48 ألفاً، ملف المزاد 141 ألفاً، ومقعد السائق يبدو كالرقم الأعلى. هذه هي السيارة. اطلب التفسير قبل أي عربون. إن كان الجواب شاشة مُستبدلة وجدة لا تذهب إلا إلى الكنيسة، فالقرار عندك.",
          "П'ять доказів не потрібні. Панель каже 48 000, аукціонна справа 141 000, а сидіння водія виглядає як більше число. Оце і є авто. Попросіть пояснення до будь-якого завдатку. Якщо відповідь це замінений екран і бабуся, яка їздила лише до церкви, рішення вже є.",
          "Пять доказательств не нужны. Панель говорит 48 000, аукционное дело 141 000, а сиденье водителя выглядит как большее число. Вот это и есть машина. Попросите объяснение до любого задатка. Если ответ это заменённый экран и бабушка, которая ездила только в церковь, решение уже есть.",
          "不用凑五条证据。表上 4.8 万，拍卖档案 14.1 万，驾驶座也像那个大数字。这就是这辆车。定金之前先让卖家解释。如果答案是换过屏幕，外加一个只开去教堂的奶奶，你已经可以走了。",
        ),
      },
    ],
  },
  {
    id: "import-scam",
    minutes: 7,
    kicker: L("Imports", "Import", "Importados", "Import", "Importi", "Import", "Import", "Внос", "იმპორტი", "الاستيراد", "Імпорт", "Импорт", "进口"),
    slug: L(
      "import-car-scams-before-you-pay",
      "import-betrug-bevor-sie-zahlen",
      "estafas-con-coches-importados",
      "arnaques-voiture-importee-avant-de-payer",
      "mashtrime-me-makina-te-importuara",
      "oszustwa-przy-aucie-z-importu",
      "tepari-la-masini-importate",
      "izmami-pri-vnosni-koli",
      "moshakhvebi-importirebul-manqanaze",
      "ihtiyalat-sayarat-mustawrada",
      "shakhraistvo-z-importnym-avto",
      "moshennichestvo-s-importnym-avto",
      "jinkou-che-pianju",
    ),
    title: L(
      "Three ways sellers rush an imported car",
      "Drei Arten, wie Verkäufer ein Importauto beschleunigen",
      "Tres formas de apurar un coche importado",
      "Trois façons de presser l'achat d'une voiture importée",
      "Tri mënyra si të nxitin një makinë të importuar",
      "Trzy sposoby, żeby pospieszyć auto z importu",
      "Trei feluri în care te grăbesc cu o mașină importată",
      "Три начина да ви пришпорват внесена кола",
      "სამი გზა, როგორ გაჩქარებენ იმპორტირებულ მანქანას",
      "ثلاث طرق يستعجلون بها سيارة مستوردة",
      "Три способи, як кваплять з імпортним авто",
      "Три способа, как торопят с импортной машиной",
      "进口车被催着成交的三种做法",
    ),
    description: L(
      "A deposit before the VIN, photos from another car, and a company that only exists in chat. The car can be real. The hurry usually is not.",
      "Anzahlung vor der VIN, Fotos von einem anderen Auto und eine Firma, die nur im Chat existiert. Das Auto kann echt sein. Die Eile meist nicht.",
      "Una señal antes del VIN, fotos de otro coche y una empresa que solo existe en el chat. El coche puede ser real. La prisa casi nunca.",
      "Des arrhes avant le VIN, des photos d'une autre voiture et une société qui n'existe que dans le chat. La voiture peut être réelle. La hâte, rarement.",
      "Kapar para VIN-it, foto nga një makinë tjetër dhe një firmë që ekziston vetëm në bisedë. Makina mund të jetë e vërtetë. Nxitimi zakonisht jo.",
      "Zadatek przed VIN, zdjęcia innego auta i firma, która istnieje tylko na czacie. Auto może być prawdziwe. Pośpiech zwykle nie.",
      "Avans înainte de VIN, poze de la altă mașină și o firmă care există doar pe chat. Mașina poate fi reală. Graba, de obicei, nu.",
      "Капаро преди VIN, снимки от друга кола и фирма, която съществува само в чата. Колата може да е истинска. Бързането обикновено не.",
      "ავანსი VIN-მდე, სხვა მანქანის ფოტოები და კომპანია, რომელიც მხოლოდ ჩათში არსებობს. მანქანა შეიძლება ნამდვილი იყოს. აჩქარება ჩვეულებრივ არა.",
      "عربون قبل رقم الهيكل، صور من سيارة أخرى، وشركة لا توجد إلا في الدردشة. السيارة قد تكون حقيقية. الاستعجال غالباً لا.",
      "Завдаток до VIN, фото іншої машини і фірма, яка є лише в чаті. Авто може бути справжнім. Поспіх зазвичай ні.",
      "Задаток до VIN, фото другой машины и фирма, которая есть только в чате. Машина может быть настоящей. Спешка обычно нет.",
      "定金在 VIN 之前，照片是另一辆车，公司只活在聊天里。车可能是真的。那股急，多半不是。",
    ),
    sections: [
      {
        h: L(
          "Money first, chassis later",
          "Erst Geld, Fahrgestell später",
          "Primero el dinero, el chasis después",
          "L'argent d'abord, le châssis ensuite",
          "Paratë së pari, shasia pastaj",
          "Najpierw pieniądze, nadwozie potem",
          "Întâi banii, șasiul pe urmă",
          "Първо парите, шасито после",
          "ჯერ ფული, შასი მერე",
          "المال أولاً والهيكل لاحقاً",
          "Спочатку гроші, шасі потім",
          "Сначала деньги, шасси потом",
          "先收钱，车架号以后再说",
        ),
        p: L(
          "The message says the car is already cleared, or that it is the last one on the list. They will send the VIN after you transfer a holding fee. Do not. The VIN is the only thing that connects the advert to a record. Without it you are holding a conversation, not a car. A seller who has the vehicle has the 17 characters on the screen the same minute you ask.",
          "Die Nachricht sagt, das Auto sei schon verzollt oder das letzte auf der Liste. Die VIN komme nach der Reservierungsgebühr. Lassen Sie das. Die VIN ist das Einzige, das die Anzeige mit einer Akte verbindet. Ohne sie halten Sie ein Gespräch, kein Auto. Wer das Fahrzeug hat, hat die 17 Zeichen in der Minute, in der Sie fragen.",
          "El mensaje dice que el coche ya está despachado, o que es el último de la lista. El VIN llega después de la reserva. No. El VIN es lo único que une el anuncio con un registro. Sin él tienes una conversación, no un coche. Quien tiene el vehículo tiene los 17 caracteres en la misma pantalla, el minuto en que los pides.",
          "Le message dit que la voiture est déjà dédouanée, ou que c'est la dernière de la liste. Le VIN viendra après les frais de réservation. Non. Le VIN est le seul lien entre l'annonce et un dossier. Sans lui vous tenez une conversation, pas une voiture. Qui a le véhicule a les 17 caractères à l'écran la minute où vous les demandez.",
          "Mesazhi thotë se makina është zhdoganuar, ose se është e fundit në listë. VIN-in e dërgojnë pasi të transferosh tarifën e mbajtjes. Mos. VIN-i është e vetmja gjë që e lidh shpalljen me një regjistër. Pa të ke një bisedë, jo një makinë. Kush e ka makinën, i ka 17 shenjat në ekran po atë minutë që i kërkon.",
          "Wiadomość mówi, że auto jest już odprawione albo że to ostatnie na liście. VIN przyjdzie po opłacie za rezerwację. Nie. VIN jest jedyną rzeczą, która łączy ogłoszenie z zapisem. Bez niego masz rozmowę, nie auto. Kto ma pojazd, ma 17 znaków na ekranie w tej samej minucie, gdy prosisz.",
          "Mesajul spune că mașina e deja vămută sau că e ultima de pe listă. VIN-ul vine după taxa de rezervare. Nu. VIN-ul e singurul lucru care leagă anunțul de o evidență. Fără el ai o conversație, nu o mașină. Cine are vehiculul are cele 17 caractere pe ecran în minutul în care le ceri.",
          "Съобщението казва, че колата вече е митнически оформена или че е последната в списъка. VIN идва след таксата за резервация. Не. VIN е единственото, което връзва обявата със запис. Без него държите разговор, не кола. Който има колата, има 17-те знака на екрана в същата минута, в която ги поискате.",
          "შეტყობინება ამბობს, მანქანა უკვე განბაჟებულია, ან სიაში ბოლოა. VIN მოვა დაჯავშნის გადასახადის შემდეგ. არა. VIN არის ერთადერთი, რაც განცხადებას ჩანაწერს უკავშირებს. მის გარეშე საუბარი გაქვთ, არა მანქანა. ვისაც მანქანა აქვს, 17 ნიშანი ეკრანზე იმავე წუთს აქვს, როცა ითხოვთ.",
          "الرسالة تقول إن السيارة خُلّصت أو إنها الأخيرة في القائمة. رقم الهيكل يأتي بعد رسوم الحجز. لا. رقم الهيكل هو الشيء الوحيد الذي يربط الإعلان بسجل. من دونه لديك حديث لا سيارة. من يملك السيارة يملك الأحرف السبعة عشر على الشاشة في الدقيقة التي تطلبها.",
          "Повідомлення каже, що авто вже розмитнене або що воно останнє в списку. VIN прийде після плати за бронювання. Ні. VIN це єдине, що зв'язує оголошення із записом. Без нього у вас розмова, не авто. Хто має машину, має 17 знаків на екрані тієї ж хвилини, коли ви просите.",
          "Сообщение говорит, что машина уже растаможена или что она последняя в списке. VIN придёт после платы за бронь. Нет. VIN это единственное, что связывает объявление с записью. Без него у вас разговор, не машина. У кого машина есть, у того 17 знаков на экране в ту же минуту, когда вы просите.",
          "消息说车已经清关，或者这是名单上最后一辆。VIN 要等你打了订金才发。别打。VIN 是广告和记录之间唯一的接头。没有它，你握住的是一段聊天，不是一辆车。车真在他手里，你一问，17 位当天就在屏幕上。",
        ),
      },
      {
        h: L(
          "The photos are often a different car",
          "Die Fotos sind oft ein anderes Auto",
          "Las fotos suelen ser de otro coche",
          "Les photos sont souvent celles d'une autre voiture",
          "Fotot shpesh janë të një makine tjetër",
          "Zdjęcia często są z innego auta",
          "Pozele sunt adesea ale altei mașini",
          "Снимките често са на друга кола",
          "ფოტოები ხშირად სხვა მანქანისაა",
          "الصور كثيراً لسيارة أخرى",
          "Фото часто з іншої машини",
          "Фото часто с другой машины",
          "照片常常是另一辆车",
        ),
        p: L(
          "Stock angles, a studio floor, a plate that is blurred on purpose. Compare the background, the wheels and a scratch that should be in every shot. Ask for a photo of the VIN plate on the body, taken in the same light as the car, with a hand or a paper in the frame. A folder of pretty pictures does not prove the car in the port is the one in the advert.",
          "Katalogwinkel, Studio-Boden, ein absichtlich unleserliches Kennzeichen. Vergleichen Sie den Hintergrund, die Felgen und einen Kratzer, der auf jedem Bild sitzen müsste. Verlangen Sie ein Foto der VIN am Blech, im selben Licht wie das Auto, mit einer Hand oder einem Zettel im Bild. Ein Ordner schöner Bilder beweist nicht, dass das Auto im Hafen das aus der Anzeige ist.",
          "Ángulos de catálogo, suelo de estudio, una matrícula desenfocada a propósito. Compara el fondo, las llantas y un arañazo que debería salir en todas. Pide una foto de la placa del VIN en la carrocería, con la misma luz que el coche y una mano o un papel en el encuadre. Una carpeta de fotos bonitas no prueba que el coche del puerto sea el del anuncio.",
          "Angles de catalogue, sol de studio, une plaque floutée exprès. Comparez le fond, les jantes et une rayure qui devrait être sur chaque photo. Demandez une photo de la plaque VIN sur la caisse, dans la même lumière que la voiture, avec une main ou un papier dans le cadre. Un dossier de belles images ne prouve pas que la voiture au port est celle de l'annonce.",
          "Foto nga çdo anë, si në katalog, dysheme studioje, dhe një targë e turbullt me qëllim. Krahaso sfondin, disqet dhe një gërvishtje që duhet të dalë në çdo foto. Kërko një foto të tabelës së VIN-it mbi kasën, me të njëjtën dritë si makina, dhe një dorë ose një letër në kornizë. Një grumbull fotosh të bukura nuk provon se makina në port është ajo e shpalljes.",
          "Kadry katalogowe, podłoga studia, tablica specjalnie rozmyta. Porównaj tło, felgi i rysę, która powinna być na każdym zdjęciu. Poproś o zdjęcie tabliczki VIN na nadwoziu, w tym samym świetle co auto, z ręką albo kartką w kadrze. Teczka ładnych zdjęć nie dowodzi, że auto w porcie to to z ogłoszenia.",
          "Unghiuri de catalog, podea de studio, o plăcuță blurată intenționat. Compară fundalul, jantele și o zgârietură care ar trebui să fie în fiecare poză. Cere o poză cu plăcuța VIN pe caroserie, în aceeași lumină ca mașina, cu o mână sau o hârtie în cadru. Un dosar de poze frumoase nu dovedește că mașina din port e cea din anunț.",
          "Каталожни ъгли, студиен под, номер умишлено размазан. Сравнете фона, джантите и драскотина, която трябва да е на всяка снимка. Поискайте снимка на табелката с VIN върху купето, на същата светлина като колата, с ръка или лист в кадъра. Папка хубави снимки не доказва, че колата на пристанището е тази от обявата.",
          "კატალოგის კუთხეები, სტუდიის იატაკი, ნომერი განზრახ ბუნდოვანი. შეადარეთ ფონი, დისკები და ნაკაწრი, რომელიც ყველა კადრში უნდა იყოს. VIN-ის ფირფიტა ძარაზე მოითხოვეთ, იმავე შუქზე, რაც მანქანა, ხელით ან ფურცლით კადრში. ლამაზი ფოტოების საქაღალდე არ ამტკიცებს, რომ პორტის მანქანა განცხადების მანქანაა.",
          "زوايا كتالوج، أرضية استوديو، لوحة مموّهة عن قصد. قارن الخلفية والعجلات وخدشاً يجب أن يظهر في كل صورة. اطلب صورة للوحة الهيكل على الجسم، بنفس ضوء السيارة، ويد أو ورقة في الإطار. مجلد صور جميلة لا يثبت أن سيارة الميناء هي سيارة الإعلان.",
          "Каталожні ракурси, підлога студії, номер навмисно розмитий. Порівняйте тло, диски і подряпину, яка має бути на кожному фото. Попросіть фото таблички VIN на кузові, у тому ж світлі, що й авто, з рукою чи папірцем у кадрі. Тека гарних фото не доводить, що авто в порту це авто з оголошення.",
          "Каталожные ракурсы, пол студии, номер специально размыт. Сравните фон, диски и царапину, которая должна быть на каждом фото. Попросите фото таблички VIN на кузове, в том же свете, что и машина, с рукой или бумажкой в кадре. Папка красивых фото не доказывает, что машина в порту это машина из объявления.",
          "目录角度、影棚地面、牌照故意糊掉。对背景、轮圈，还有一条应该每张都在的划痕。要一张车身上的 VIN 铭牌，光线和车子同一套，画面里放一只手或一张纸。一文件夹好看的图，证明不了港口那辆就是广告这辆。",
        ),
      },
      {
        h: L(
          "A logo in the chat is not a company",
          "Ein Logo im Chat ist keine Firma",
          "Un logo en el chat no es una empresa",
          "Un logo dans le chat n'est pas une société",
          "Një logo në bisedë nuk është firmë",
          "Logo na czacie to nie firma",
          "Un logo pe chat nu e o firmă",
          "Лого в чата не е фирма",
          "ლოგო ჩათში კომპანია არ არის",
          "شعار في الدردشة ليس شركة",
          "Логотип у чаті це не фірма",
          "Логотип в чате это не фирма",
          "聊天里的标志不是一家公司",
        ),
        p: L(
          "The name on WhatsApp can be a shipping line, a dealer, or a word that sounds like both. Ask for an address you can find on a map, a registration number, and a person who will answer a normal call. Money sent to a personal name for a car that is still in a container is very hard to get back once the number goes quiet.",
          "Der Name bei WhatsApp kann eine Reederei, ein Händler oder ein Wort sein, das nach beidem klingt. Verlangen Sie eine Adresse, die Sie auf der Karte finden, eine Registernummer und eine Person, die einen gewöhnlichen Anruf annimmt. Geld auf einen privaten Namen für ein Auto, das noch im Container steht, kommt kaum zurück, sobald die Nummer schweigt.",
          "El nombre en WhatsApp puede ser una naviera, un concesionario o una palabra que suena a las dos. Pide una dirección que puedas ver en el mapa, un número de registro y una persona que conteste una llamada normal. El dinero enviado a un nombre personal por un coche que sigue en un contenedor cuesta mucho recuperarlo cuando el número se calla.",
          "Le nom sur WhatsApp peut être une compagnie maritime, un marchand, ou un mot qui ressemble aux deux. Demandez une adresse que vous trouvez sur une carte, un numéro d'immatriculation et une personne qui répond à un appel ordinaire. L'argent envoyé à un nom personnel pour une voiture encore dans un conteneur revient très mal dès que le numéro se tait.",
          "Emri në WhatsApp mund të jetë një linjë transporti, një tregtar, ose një fjalë që tingëllon si të dyja. Kërko një adresë që e gjen në hartë, një numër regjistrimi dhe një njeri që përgjigjet në një telefon normal. Paratë dërguar në një emër personal për një makinë që është ende në kontejner kthehen shumë vështirë sapo numri hesht.",
          "Nazwa na WhatsAppie może być armatorem, handlarzem albo słowem, które brzmi jak oba. Poproś o adres, który znajdziesz na mapie, numer rejestracji i osobę, która odbierze zwykły telefon. Pieniądze wysłane na prywatne nazwisko za auto, które wciąż jest w kontenerze, bardzo trudno odzyskać, gdy numer milknie.",
          "Numele de pe WhatsApp poate fi o linie de shipping, un dealer sau un cuvânt care sună a ambele. Cere o adresă pe care o găsești pe hartă, un număr de înregistrare și o persoană care răspunde la un apel obișnuit. Banii trimiși pe un nume personal pentru o mașină încă în container se recuperează foarte greu când numărul tace.",
          "Името в WhatsApp може да е корабна линия, търговец или дума, която звучи като и двете. Поискайте адрес, който се намира на картата, регистрационен номер и човек, който вдига обикновено обаждане. Пари, пратени на лично име за кола, която още е в контейнер, много трудно се връщат, щом номерът млъкне.",
          "სახელი WhatsApp-ზე შეიძლება იყოს გადამზიდი, დილერი, ან სიტყვა, რომელიც ორივეს ჰგავს. მისამართი ითხოვეთ, რომელსაც რუკაზე იპოვით, სარეგისტრაციო ნომერი და ადამიანი, რომელიც ჩვეულებრივ ზარს პასუხობს. პირად სახელზე გაგზავნილი ფული მანქანისთვის, რომელიც ჯერ კონტეინერშია, ძალიან ძნელად ბრუნდება, როცა ნომერი დუმს.",
          "الاسم في واتساب قد يكون خط شحن أو تاجراً أو كلمة تشبه الاثنين. اطلب عنواناً تجده على الخريطة، ورقم تسجيل، وشخصاً يرد على اتصال عادي. المال المُرسل إلى اسم شخصي لسيارة ما زالت في حاوية يصعب جداً استرداده حين يصمت الرقم.",
          "Ім'я у WhatsApp може бути лінією перевезення, дилером або словом, яке звучить як обидва. Попросіть адресу, яку знайдете на карті, реєстраційний номер і людину, яка відповість на звичайний дзвінок. Гроші на особисте ім'я за авто, яке ще в контейнері, дуже важко повернути, щойно номер замовкає.",
          "Имя в WhatsApp может быть линией перевозки, дилером или словом, которое звучит как оба. Попросите адрес, который найдёте на карте, регистрационный номер и человека, который ответит на обычный звонок. Деньги на личное имя за машину, которая ещё в контейнере, очень трудно вернуть, как только номер замолкает.",
          "WhatsApp 上的名字可以是船公司，可以是车商，也可以是听起来两边都像的一个词。要一个地图上找得到的地址、一个注册号、一个会接普通电话的人。车还在箱子里，钱打到个人名字上，号码一安静，很难追回来。",
        ),
      },
      {
        h: L(
          "A slow check is the cheap part",
          "Eine langsame Prüfung ist der günstige Teil",
          "Una comprobación lenta es la parte barata",
          "Un contrôle lent est la part bon marché",
          "Një kontroll i ngadaltë është pjesa e lirë",
          "Powolne sprawdzenie jest tanią częścią",
          "O verificare mai lentă e partea ieftină",
          "Бавната проверка е евтината част",
          "ნელი შემოწმება იაფი ნაწილია",
          "الفحص البطيء هو الجزء الرخيص",
          "Повільна перевірка це дешева частина",
          "Медленная проверка это дешёвая часть",
          "慢慢查，才是便宜的那一步",
        ),
        p: L(
          "The report costs less than the train ticket to see a car that was never yours. Get the VIN, read kilometres, repairs, salvage and theft, and match the file to the photos you were sent. If the seller cannot wait for that, the car was never waiting for you.",
          "Der Bericht kostet weniger als die Fahrkarte zu einem Auto, das nie Ihres war. Holen Sie die VIN, lesen Sie Kilometer, Reparaturen, Totalschaden und Diebstahl und legen Sie die Akte neben die Fotos. Wer darauf nicht warten kann, hat das Auto nie für Sie bereithalten.",
          "El informe cuesta menos que el billete para ver un coche que nunca fue tuyo. Pide el VIN, lee kilómetros, reparaciones, pérdida total y robo, y junta el archivo con las fotos que te mandaron. Si el vendedor no puede esperar eso, el coche nunca te estaba esperando.",
          "Le rapport coûte moins que le billet pour voir une voiture qui n'a jamais été la vôtre. Prenez le VIN, lisez kilomètres, réparations, épave et vol, et posez le fichier à côté des photos reçues. Si le vendeur ne peut pas attendre cela, la voiture ne vous attendait pas.",
          "Raporti kushton më pak se bileta për të parë një makinë që s'ka qenë kurrë jotja. Merr VIN-in, lexo kilometrat, riparimet, dëmtimin total dhe vjedhjen, dhe krahaso raportin me fotot që të kanë dërguar. Nëse shitësi s'pret dot kaq, makina s'ka qenë duke të pritur ty.",
          "Raport kosztuje mniej niż bilet, żeby zobaczyć auto, które nigdy nie było twoje. Weź VIN, przeczytaj kilometry, naprawy, szkodę całkowitą i kradzież i złóż plik ze zdjęciami, które dostałeś. Jeśli sprzedawca nie może na to poczekać, auto nigdy na ciebie nie czekało.",
          "Raportul costă mai puțin decât biletul ca să vezi o mașină care n-a fost niciodată a ta. Ia VIN-ul, citește kilometrii, reparațiile, dauna totală și furtul și potrivește dosarul cu pozele primite. Dacă vânzătorul nu poate aștepta asta, mașina nu te aștepta.",
          "Отчетът струва по-малко от билета до кола, която никога не е била ваша. Вземете VIN, прочетете километри, ремонти, тотал и кражба и сложете файла до снимките, които са ви пратили. Ако продавачът не може да изчака това, колата никога не ви е чакала.",
          "ანგარიში ნაკლები ღირს, ვიდრე ბილეთი მანქანამდე, რომელიც არასდროს ყოფილა თქვენი. VIN აიღეთ, წაიკითხეთ კილომეტრები, რემონტი, სალვაჟი და ქურდობა და საქმე გამოგზავნილ ფოტოებს შეუსაბამეთ. თუ გამყიდველი ამას ვერ ითმენს, მანქანა არასდროს გელოდებოდათ.",
          "التقرير أرخص من تذكرة لرؤية سيارة لم تكن لك يوماً. خذ رقم الهيكل، اقرأ الكيلومترات والتصليحات والخسارة الكاملة والسرقة، وطابق الملف مع الصور التي أُرسلت إليك. إن لم يستطع البائع انتظار ذلك فالسيارة لم تكن تنتظرك.",
          "Звіт коштує менше за квиток до авто, яке ніколи не було вашим. Візьміть VIN, прочитайте кілометри, ремонти, тотал і викрадення і звірте файл із фото, які вам надіслали. Якщо продавець не може цього зачекати, авто ніколи на вас не чекало.",
          "Отчёт стоит меньше билета до машины, которая никогда не была вашей. Возьмите VIN, прочитайте километры, ремонты, тотал и угон и сверьте файл с фото, которые вам прислали. Если продавец не может этого подождать, машина никогда вас не ждала.",
          "一份报告比车票便宜，那趟车票是去看一辆从来不是你的车。先要 VIN，读公里、维修、全损和盗抢，再拿档案去对给你的照片。卖家等不了这一步，这车本来就没在等你。",
        ),
      },
    ],
  },
];
