import type { Language } from "@/lib/languages";

const LANGS = [
  "en", "de", "es", "fr", "sq", "pl", "ro", "bg", "ka", "ar", "uk", "ru", "zh",
] as const satisfies readonly Language[];

type L = Record<Language, string>;

function L(...values: readonly string[]): L {
  const out = {} as L;
  LANGS.forEach((lang, i) => {
    out[lang] = values[i] ?? values[0] ?? "";
  });
  return out;
}

export type DepthSection = { h: L; p: L; figure?: string };

export const BLOG_DEPTH: Record<string, DepthSection[]> = {
  "free-km": [
    {
      figure: "/blog/inline/free-km.jpg",
      h: L(
        "Write both numbers down before you call",
        "Schreiben Sie beide Zahlen auf, bevor Sie anrufen",
        "Anota los dos números antes de llamar",
        "Notez les deux chiffres avant d'appeler",
        "Shkruaji të dyja shifrat para se të telefonosh",
        "Zapisz obie liczby, zanim zadzwonisz",
        "Notează ambele cifre înainte să suni",
        "Запишете и двете числа, преди да се обадите",
        "ორივე რიცხვი ჩაიწერეთ, სანამ დარეკავთ",
        "اكتب الرقمين قبل أن تتصل",
        "Запишіть обидва числа, перш ніж дзвонити",
        "Запишите оба числа, прежде чем звонить",
        "打电话之前，先把两个数字写下来",
      ),
      p: L(
        "Write the number on the dash and the oldest number you can find, with the date and where it came from. A photo of today's dashboard cannot argue with a line from two years ago. If you only have the advert, you only have today's claim.",
        "Notieren Sie die Zahl am Tacho und die älteste Zahl, die Sie finden, mit Datum und Herkunft. Ein Foto vom heutigen Cockpit gewinnt nicht gegen eine Zeile von vor zwei Jahren. Wer nur die Anzeige hat, hat nur die Behauptung von heute.",
        "Anota el número del tablero y el número más viejo que encuentres, con la fecha y de dónde salió. Una foto del tablero de hoy no puede discutir con una línea de hace dos años. Si solo tienes el anuncio, solo tienes la versión de hoy.",
        "Notez le chiffre au tableau et le plus ancien que vous trouvez, avec la date et l'origine. Une photo du tableau d'aujourd'hui ne gagne pas contre une ligne d'il y a deux ans. Si vous n'avez que l'annonce, vous n'avez que la version du jour.",
        "Shkruaj shifrën te paneli dhe shifrën më të vjetër që gjen, me datën dhe ku e ke gjetur. Një foto e panelit të sotëm nuk ia del një rreshti të dy viteve më parë. Nëse ke vetëm shpalljen, ke vetëm atë që thonë sot.",
        "Zapisz liczbę na liczniku i najstarszą, jaką znajdziesz, z datą i źródłem. Zdjęcie dzisiejszego licznika nie wygra z linijką sprzed dwóch lat. Jak masz tylko ogłoszenie, masz tylko dzisiejszą wersję.",
        "Notează cifra de pe bord și cea mai veche pe care o găsești, cu data și sursa. O poză a bordului de azi nu câștigă în fața unui rând de acum doi ani. Dacă ai doar anunțul, ai doar varianta de azi.",
        "Запишете цифрата на таблото и най-старата, която намерите, с датата и откъде е. Снимка на днешното табло не печели срещу ред отпреди две години. Ако имате само обявата, имате само днешната версия.",
        "ჩაიწერეთ დაფის რიცხვი და უძველესი, რასაც იპოვით, თარიღითა და წყაროთი. დღევანდელი დაფის ფოტო ორი წლის წინანდელ სტრიქონს ვერ სჯობნის. თუ მხოლოდ განცხადება გაქვთ, მხოლოდ დღევანდელი ვერსია გაქვთ.",
        "اكتب رقم العداد وأقدم رقم تجده، مع التاريخ ومن أين جاء. صورة عداد اليوم لا تغلب سطراً من قبل سنتين. إن كان معك الإعلان فقط، فمعك رواية اليوم فقط.",
        "Запишіть цифру на панелі і найстарішу, яку знайдете, з датою і звідки вона. Фото сьогоднішньої панелі не переважить рядок дворічної давнини. Якщо є лише оголошення, є лише сьогоднішня версія.",
        "Запишите цифру на панели и самую старую, какую найдёте, с датой и откуда она. Фото сегодняшней панели не перевесит строку двухлетней давности. Если есть только объявление, есть только сегодняшняя версия.",
        "把仪表上的数字和你能找到的最早数字写下来，带上日期和出处。今天仪表盘的照片，争不过两年前的一行记录。如果手里只有广告，你就只有今天这一版说法。",
      ),
    },
    {
      h: L(
        "A useful line has a date on it",
        "Eine brauchbare Zeile hat ein Datum",
        "Una línea útil lleva fecha",
        "Une ligne utile a une date",
        "Një rresht i dobishëm ka datë",
        "Przydatna linijka ma datę",
        "Un rând util are o dată",
        "Полезният ред има дата",
        "სასარგებლო სტრიქონს თარიღი აქვს",
        "السطر المفيد عليه تاريخ",
        "Корисний рядок має дату",
        "Полезная строка с датой",
        "有用的那一行带着日期",
      ),
      p: L(
        "A kilometre figure with no date is a number someone can move. Auction sheets, service visits and border records matter because they say when the car showed that figure. If an older line is higher than the dash today, that is the check. You do not need a longer story than that.",
        "Ein Kilometerwert ohne Datum ist eine Zahl, die sich verschieben lässt. Auktionsbögen, Werkstattbesuche und Grenzvermerke zählen, weil sie sagen, wann das Auto diese Zahl gezeigt hat. Ist eine ältere Zeile höher als der Tacho heute, ist das die Prüfung. Mehr Geschichte brauchen Sie nicht.",
        "Una cifra de kilómetros sin fecha es un número que alguien puede mover. Las fichas de subasta, las visitas al taller y los registros de frontera importan porque dicen cuándo el coche mostró esa cifra. Si una línea más vieja es más alta que el tablero de hoy, esa es la comprobación. No hace falta una historia más larga.",
        "Un chiffre de kilomètres sans date est un nombre que l'on peut déplacer. Les fiches d'enchères, les passages atelier et les relevés de frontière comptent parce qu'ils disent quand la voiture affichait ce chiffre. Si une ligne plus ancienne est plus haute que le tableau d'aujourd'hui, c'est le contrôle. Vous n'avez pas besoin d'une histoire plus longue.",
        "Një shifër kilometrash pa datë është numër që dikush mund ta lëvizë. Fletët e ankandit, vizitat në servis dhe shënimet e doganës kanë vlerë sepse thonë kur e ka treguar makina atë shifër. Nëse një rresht më i vjetër është më i lartë se paneli sot, ky është kontrolli. Nuk të duhet histori më e gjatë se kaq.",
        "Liczba kilometrów bez daty to cyfra, którą ktoś może przesunąć. Karty aukcyjne, wizyty w serwisie i zapisy z granicy są ważne, bo mówią, kiedy auto pokazało tę liczbę. Jeśli starsza linijka jest wyższa niż licznik dziś, to jest sprawdzenie. Dłuższej historii nie potrzebujesz.",
        "O cifră de kilometri fără dată e un număr pe care cineva îl poate muta. Fișele de licitație, vizitele la service și înregistrările de la graniță contează pentru că spun când mașina a arătat cifra aia. Dacă un rând mai vechi e mai mare decât bordul de azi, asta e verificarea. Nu îți trebuie o poveste mai lungă.",
        "Цифра за километри без дата е число, което някой може да премести. Тръжните листове, сервизните посещения и граничните записи имат значение, защото казват кога колата е показала тази цифра. Ако по-стар ред е по-висок от таблото днес, това е проверката. По-дълга история не ви трябва.",
        "კილომეტრი თარიღის გარეშე რიცხვია, რომლის გადატანაც შეიძლება. აუქციონის ფურცლები, სერვისის ვიზიტები და საზღვრის ჩანაწერები იმიტომაა მნიშვნელოვანი, რომ ამბობენ, როდის აჩვენა მანქანამ ეს რიცხვი. თუ ძველი სტრიქონი დღევანდელ დაფაზე მაღალია, ეს არის შემოწმება. უფრო გრძელი ამბავი არ გჭირდებათ.",
        "رقم كيلومترات بلا تاريخ هو عدد يمكن لشخص أن يحرّكه. أوراق المزاد وزيارات الصيانة وسجلات الحدود مهمة لأنها تقول متى أظهرت السيارة هذا الرقم. إذا كان سطر أقدم أعلى من عداد اليوم، فهذا هو الفحص. لا تحتاج قصة أطول من ذلك.",
        "Цифра кілометрів без дати це число, яке хтось може зсунути. Аукціонні листи, візити на сервіс і записи з кордону важливі, бо кажуть, коли авто показало цю цифру. Якщо старіший рядок вищий за панель сьогодні, це і є перевірка. Довшої історії не треба.",
        "Цифра километров без даты это число, которое кто-то может сдвинуть. Аукционные листы, визиты на сервис и пограничные записи важны, потому что говорят, когда машина показала эту цифру. Если более старая строка выше панели сегодня, это и есть проверка. Более длинной истории не нужно.",
        "没有日期的公里数，只是一个可以被改动的数字。拍卖单、保养记录和过境记录有用，是因为它们写明了这辆车在什么时候显示出这个数字。如果更早的一行比今天的仪表更高，这就是核查。不需要比这更长的故事。",
      ),
    },
  ],
  "read-vin": [
    {
      figure: "/vin-help/door-jamb-vin.jpg",
      h: L(
        "Read the metal, not only the sticker",
        "Lesen Sie das Blech, nicht nur den Aufkleber",
        "Lee el metal, no solo la pegatina",
        "Lisez le métal, pas seulement l'étiquette",
        "Lexo metalin, jo vetëm ngjitësen",
        "Czytaj metal, nie tylko naklejkę",
        "Citește metalul, nu doar autocolantul",
        "Четете метала, не само стикера",
        "წაიკითხეთ ლითონი, არა მხოლოდ სტიკერი",
        "اقرأ المعدن، لا الملصق وحده",
        "Читайте метал, не лише наклейку",
        "Читайте металл, не только наклейку",
        "读金属上的字，别只读贴纸",
      ),
      p: L(
        "The sticker on the door is easy to reprint. The characters pressed into the body, and the strip at the bottom of the windscreen, are harder to swap while the car is in front of you. Read all three in the same light. If one character differs, stop before you talk about price.",
        "Der Aufkleber in der Tür lässt sich nachdrucken. Die in die Karosserie geprägten Zeichen und der Streifen unten an der Scheibe sind schwerer zu tauschen, solange das Auto vor Ihnen steht. Lesen Sie alle drei im gleichen Licht. Wenn ein Zeichen abweicht, hören Sie auf, bevor Sie über den Preis reden.",
        "La pegatina de la puerta se reimprime fácil. Los caracteres marcados en la carrocería y la tira bajo el parabrisas son más difíciles de cambiar con el coche delante. Lee los tres con la misma luz. Si un carácter cambia, para antes de hablar de precio.",
        "L'étiquette de porte se réimprime facilement. Les caractères frappés dans la caisse et la bande en bas du pare-brise sont plus difficiles à échanger tant que la voiture est devant vous. Lisez les trois dans la même lumière. Si un caractère diffère, arrêtez avant de parler prix.",
        "Ngjitësja e derës ribëhet lehtë. Shenjat e shtypura në karroceri dhe shiriti në fund të xhamit ndërrohen më vështirë kur makina është para teje. Lexoji të treja në të njëjtën dritë. Nëse një shenjë ndryshon, ndalo para se të flasësh për çmimin.",
        "Naklejkę w drzwiach łatwo wydrukować od nowa. Znaki wybite w karoserii i pasek u dołu szyby trudniej podmienić, kiedy auto stoi przed tobą. Przeczytaj wszystkie trzy w tym samym świetle. Jeśli jeden znak się różni, zatrzymaj się, zanim zaczniesz o cenę.",
        "Autocolantul ușii se retipărește ușor. Caracterele presate în caroserie și banda de jos a parbrizului se schimbă mai greu cât mașina e în fața ta. Citește-le pe toate trei în aceeași lumină. Dacă un caracter diferă, oprește-te înainte să vorbești de preț.",
        "Стикерът на вратата се препечатва лесно. Знаците, вбити в купето, и лентата долу на стъклото се сменят по-трудно, докато колата е пред вас. Прочетете и трите на една и съща светлина. Ако един знак се различава, спрете, преди да говорите за цена.",
        "კარის სტიკერის ხელახლა დაბეჭდვა ადვილია. ძარაში დატანილი ნიშნები და მინის ქვედა ზოლი უფრო ძნელად იცვლება, სანამ მანქანა თქვენს წინ დგას. სამივე ერთსა და იმავე შუქზე წაიკითხეთ. თუ ერთი ნიშანი განსხვავდება, ფასზე საუბრამდე გაჩერდით.",
        "ملصق الباب يُعاد طبعه بسهولة. الرموز المضغوطة في الهيكل والشريط أسفل الزجاج أصعب تبديلاً والسيارة أمامك. اقرأ الثلاثة في الضوء نفسه. إذا اختلف رمز واحد، توقف قبل الحديث عن السعر.",
        "Наклейку на дверях легко надрукувати заново. Знаки, вбиті в кузов, і смужку внизу скла важче підмінити, поки авто стоїть перед вами. Прочитайте всі три при тому самому світлі. Якщо один знак відрізняється, зупиніться до розмови про ціну.",
        "Наклейку на двери легко напечатать заново. Знаки, выбитые в кузове, и полоску внизу стекла труднее подменить, пока машина стоит перед вами. Прочитайте все три при том же свете. Если один знак отличается, остановитесь до разговора о цене.",
        "车门上的贴纸很好重印。打在车身上的字符，以及挡风玻璃下沿那一条，车停在你面前时更难换掉。三处用同一束光读。有一个字符对不上，在谈价格之前就停。",
      ),
    },
    {
      figure: "/blog/inline/read-vin.jpg",
      h: L(
        "A photo in the chat is easy to swap",
        "Ein Foto im Chat lässt sich leicht tauschen",
        "Una foto en el chat se cambia fácil",
        "Une photo dans le chat s'échange facilement",
        "Një foto në chat ndërrohet lehtë",
        "Zdjęcie na czacie łatwo podmienić",
        "O poză în chat se schimbă ușor",
        "Снимка в чата се сменя лесно",
        "ჩატის ფოტო ადვილად იცვლება",
        "صورة في المحادثة يسهل تبديلها",
        "Фото в чаті легко підмінити",
        "Фото в чате легко подменить",
        "聊天里的照片很好换",
      ),
      p: L(
        "Ask for the plate still on the car, taken that day, with your hand or a piece of paper in the frame. Then type the 17 characters yourself. Copying them from the message is how you end up checking a different car.",
        "Bitten Sie um ein Foto vom selben Tag, die Nummer noch am Auto, Ihre Hand oder ein Blatt Papier im Bild. Tippen Sie die 17 Zeichen danach selbst. Wer sie aus der Nachricht kopiert, prüft am Ende ein anderes Auto.",
        "Pide la placa todavía en el coche, hecha ese día, con tu mano o un papel en el encuadre. Luego escribe tú los 17 caracteres. Copiarlos del mensaje es como acabar comprobando otro coche.",
        "Demandez la plaque encore sur la voiture, prise ce jour-là, avec votre main ou une feuille dans le cadre. Puis tapez les 17 caractères vous-même. Les copier depuis le message, c'est finir par contrôler une autre voiture.",
        "Kërko foton e targës ende mbi makinë, të bërë atë ditë, me dorën tënde ose një letër në kornizë. Pastaj i shkruaj vetë 17 shenjat. Nëse i kopjon nga mesazhi, përfundon duke kontrolluar një makinë tjetër.",
        "Poproś o zdjęcie tabliczki wciąż na aucie, zrobione tego dnia, z twoją ręką albo kartką w kadrze. Potem wpisz 17 znaków sam. Kopiowanie z wiadomości kończy się sprawdzaniem innego auta.",
        "Cere placa încă pe mașină, făcută în ziua aia, cu mâna ta sau o foaie în cadru. Apoi tastează tu cele 17 caractere. Dacă le copiezi din mesaj, ajungi să verifici altă mașină.",
        "Поискайте табелата още на колата, снимана същия ден, с вашата ръка или лист в кадъра. После напишете 17-те знака сами. Копирането от съобщението свършва с проверка на друга кола.",
        "ითხოვეთ ფირფიტა ჯერ კიდევ მანქანაზე, იმ დღეს გადაღებული, თქვენი ხელით ან ფურცლით კადრში. მერე 17 ნიშანი თვითონ აკრიფეთ. შეტყობინებიდან კოპირება სხვა მანქანის შემოწმებით მთავრდება.",
        "اطلب اللوحة وهي ما زالت على السيارة، مصوّرة في ذلك اليوم، ويدك أو ورقة في الإطار. ثم اكتب الرموز السبعة عشر بنفسك. نسخها من الرسالة ينتهي بفحص سيارة أخرى.",
        "Попросіть табличку ще на авто, зняту того дня, з вашою рукою чи аркушем у кадрі. Потім наберіть 17 знаків самі. Копія з повідомлення закінчується перевіркою іншого авто.",
        "Попросите табличку ещё на машине, снятую в тот день, с вашей рукой или листом в кадре. Потом наберите 17 знаков сами. Копия из сообщения заканчивается проверкой другой машины.",
        "要车牌还在车上的当天照片，镜头里有你的手或一张纸。然后你自己把这 17 位敲进去。从消息里复制，最后查到的是另一辆车。",
      ),
    },
  ],
  rollback: [
    {
      figure: "/blog/inline/rollback.jpg",
      h: L(
        "The parts wear on a different clock",
        "Die Teile altern nach einer anderen Uhr",
        "Las piezas se gastan con otro reloj",
        "Les pièces s'usent sur une autre horloge",
        "Pjesët lodhen me një orë tjetër",
        "Części zużywają się w innym tempie",
        "Piesele se uzează pe alt ceas",
        "Частите се износват по друг часовник",
        "ნაწილები სხვა საათით ცვდება",
        "الأجزاء تبلى بساعة أخرى",
        "Деталі зношуються за іншим годинником",
        "Детали изнашиваются по другим часам",
        "零件按另一套时间在磨损",
      ),
      p: L(
        "Belts, pedal rubber and the crease in the driver's seat follow years of use. A workshop can point at them. They still do not replace a logged kilometre. If the car looks this used, the next question is where the older number is.",
        "Riemen, Pedalgummi und die Falte im Fahrersitz folgen den Jahren. Eine Werkstatt kann darauf zeigen. Sie ersetzen keine gespeicherte Kilometerzahl. Sieht das Auto so benutzt aus, ist die nächste Frage, wo die ältere Zahl steht.",
        "Las correas, la goma de los pedales y el pliegue del asiento del conductor siguen los años de uso. Un taller puede señalarlos. No sustituyen un kilómetro registrado. Si el coche se ve así de usado, la siguiente pregunta es dónde está el número más viejo.",
        "Courroies, gomme des pédales et pli du siège conducteur suivent les années d'usage. Un atelier peut les montrer. Ils ne remplacent pas un kilométrage enregistré. Si la voiture a l'air si utilisée, la question suivante est: où est le chiffre plus ancien?",
        "Rripat, goma e pedalëve dhe pala e sediljes së shoferit ndjekin vitet e përdorimit. Servisi mund të t'i tregojë. Ato prapë nuk e zëvendësojnë një kilometër të shënuar. Nëse makina duket kaq e përdorur, pyetja tjetër është ku është shifra më e vjetër.",
        "Paski, guma pedałów i zagięcie fotela kierowcy idą za latami użytkowania. Warsztat może je pokazać. Nadal nie zastępują zapisanego kilometra. Jeśli auto wygląda na tak zużyte, następne pytanie brzmi: gdzie jest starsza liczba?",
        "Curelele, cauciucul pedalelor și cuta scaunului șoferului urmează anii de utilizare. Un service le poate arăta. Tot nu înlocuiesc un kilometru înregistrat. Dacă mașina arată atât de folosită, întrebarea următoare e unde e cifra mai veche.",
        "Ремъците, гумата на педалите и гънката на шофьорската седалка следват годините употреба. Сервизът може да ги посочи. Те пак не заместват записан километър. Ако колата изглежда толкова използвана, следващият въпрос е къде е по-старото число.",
        "ღვედები, პედლის რეზინი და მძღოლის სავარძლის ნაკეცი გამოყენების წლებს მიჰყვება. სერვისს შეუძლია გიჩვენოთ. ისინი მაინც ვერ ცვლიან ჩაწერილ კილომეტრს. თუ მანქანა ასე გაცვეთილად გამოიყურება, შემდეგი კითხვაა, სად არის ძველი რიცხვი.",
        "السيور ومطاط الدواسات وتجعيدة مقعد السائق تتبع سنوات الاستعمال. الورشة تستطيع الإشارة إليها. لكنها لا تغني عن كيلومتر مسجّل. إذا بدت السيارة بهذا الاستعمال، السؤال التالي هو أين الرقم الأقدم.",
        "Ремені, гума педалей і згин сидіння водія йдуть за роками використання. Сервіс може їх показати. Вони все одно не замінюють записаний кілометр. Якщо авто виглядає настільки вживаним, наступне питання: де старіше число?",
        "Ремни, резина педалей и складка сиденья водителя следуют годам использования. Сервис может их показать. Они всё равно не заменяют записанный километр. Если машина выглядит настолько поехавшей, следующий вопрос: где более старое число?",
        "皮带、踏板胶皮和驾驶座上的褶皱跟着用了多少年走。修理厂可以指给你看。它们仍然代替不了一条登记过的公里。如果这车看起来这么用过，下一个问题就是：更早的那个数字在哪里。",
      ),
    },
    {
      h: L(
        "One older number is enough",
        "Eine ältere Zahl reicht",
        "Un número más viejo basta",
        "Un seul chiffre plus ancien suffit",
        "Mjafton një shifër më e vjetër",
        "Wystarczy jedna starsza liczba",
        "Ajunge o singură cifră mai veche",
        "Едно по-старо число стига",
        "ერთი ძველი რიცხვი საკმარისია",
        "رقم أقدم واحد يكفي",
        "Досить одного старішого числа",
        "Хватает одного более старого числа",
        "一个更早的数字就够了",
      ),
      p: L(
        "You do not need a full service book to leave. If a record from an earlier year shows more kilometres than the dash shows today, the dash was changed or the line is about another car. Either way you stop. Ask the seller to explain that one line before you travel.",
        "Sie brauchen kein volles Serviceheft, um zu gehen. Zeigt ein Beleg aus einem früheren Jahr mehr Kilometer als der Tacho heute, wurde der Tacho geändert oder die Zeile gehört zu einem anderen Auto. In beiden Fällen hören Sie auf. Lassen Sie sich diese eine Zeile erklären, bevor Sie fahren.",
        "No necesitas el libro de servicio completo para irte. Si un registro de un año anterior muestra más kilómetros que el tablero hoy, el tablero se cambió o la línea es de otro coche. En los dos casos paras. Pide que te expliquen esa línea antes de viajar.",
        "Vous n'avez pas besoin du carnet complet pour partir. Si un relevé d'une année plus ancienne montre plus de kilomètres que le tableau aujourd'hui, le compteur a été changé ou la ligne concerne une autre voiture. Dans les deux cas vous vous arrêtez. Faites expliquer cette ligne avant de vous déplacer.",
        "Nuk të duhet servisi i plotë për t'u larguar. Nëse një shënim i një viti më të hershëm tregon më shumë kilometra se paneli sot, paneli është ndryshuar ose rreshti është për një makinë tjetër. Në të dyja rastet ndalon. Kërkoji shitësit ta shpjegojë atë rresht para se të nisësh rrugën.",
        "Nie potrzebujesz całej książki serwisowej, żeby odejść. Jeśli zapis z wcześniejszego roku pokazuje więcej kilometrów niż licznik dziś, licznik zmieniono albo linijka dotyczy innego auta. W obu przypadkach przestajesz. Niech sprzedawca wyjaśni tę jedną linijkę, zanim pojedziesz.",
        "Nu ai nevoie de toată cartea de service ca să pleci. Dacă o înregistrare dintr-un an mai vechi arată mai mulți kilometri decât bordul azi, bordul a fost schimbat sau rândul e despre altă mașină. În ambele cazuri te oprești. Cere-i vânzătorului să explice acel rând înainte să pleci la drum.",
        "Не ви трябва пълна сервизна книжка, за да си тръгнете. Ако запис от по-ранна година показва повече километри от таблото днес, таблото е сменено или редът е за друга кола. И в двата случая спирате. Нека продавачът обясни този ред, преди да пътувате.",
        "წასასვლელად სრული სერვისის წიგნი არ გჭირდებათ. თუ ადრინდელი წლის ჩანაწერი დღევანდელ დაფაზე მეტ კილომეტრს აჩვენებს, დაფა შეცვლილია ან სტრიქონი სხვა მანქანაზეა. ორივე შემთხვევაში ჩერდებით. გამგზავრებამდე სთხოვეთ გამყიდველს, ეს ერთი სტრიქონი აგიხსნათ.",
        "لا تحتاج دفتر صيانة كاملاً لترحل. إذا أظهر سجل من سنة أقدم كيلومترات أكثر مما يظهره العداد اليوم، فالعداد تغيّر أو السطر لسيارة أخرى. في الحالتين تتوقف. اطلب من البائع شرح هذا السطر قبل أن تسافر.",
        "Повна сервісна книжка не потрібна, щоб піти. Якщо запис з ранішого року показує більше кілометрів, ніж панель сьогодні, панель змінили або рядок про інше авто. В обох випадках ви зупиняєтесь. Нехай продавець пояснить цей рядок до поїздки.",
        "Полная сервисная книжка не нужна, чтобы уйти. Если запись более раннего года показывает больше километров, чем панель сегодня, панель меняли или строка о другой машине. В обоих случаях вы останавливаетесь. Пусть продавец объяснит эту строку до поездки.",
        "你不需要一整本保养记录才离开。如果更早一年的记录比今天仪表上的公里更高，要么仪表被改过，要么那一行是另一辆车。两种情况都该停。上路之前，让卖家把那一行说清楚。",
      ),
    },
  ],
  salvage: [
    {
      figure: "/blog/inline/salvage.jpg",
      h: L(
        "Fixed for the road, still written off",
        "Für die Straße hergerichtet, trotzdem abgeschrieben",
        "Apta para circular, y aun así dada por perdida",
        "Remise sur la route, quand même déclarée perdue",
        "E përshtatur për rrugë, prapë e nxjerrë jashtë",
        "Dopuszczona na drogę, a jednak spisana",
        "Legală pe drum, totuși casată",
        "Пускова на пътя, пак отписана",
        "გზაზე დაშვებული, მაინც ჩამოწერილი",
        "صالحة للطريق وما زالت مشطوبة",
        "Допущена на дорогу, і все одно списана",
        "Допущена на дорогу, и всё равно списана",
        "可以上路，记录上仍是报废",
      ),
      p: L(
        "A car can be made legal to drive again after the insurer paid it out. Fresh paint and a new inspection do not erase that decision. The record keeps the fact that the repair was judged too expensive at the time. Price the car as that car.",
        "Ein Auto kann wieder zulassungsfähig sein, nachdem der Versicherer gezahlt hat. Frischer Lack und eine neue Prüfung löschen diese Entscheidung nicht. Die Akte hält fest, dass die Reparatur damals als zu teuer galt. Setzen Sie den Preis für genau dieses Auto an.",
        "Un coche puede volver a ser legal para circular después de que el seguro pagó. La pintura nueva y una inspección reciente no borran esa decisión. El registro guarda que entonces la reparación se consideró demasiado cara. Ponle precio a ese coche, no a otro.",
        "Une voiture peut redevenir légale sur la route après le paiement de l'assureur. Une peinture fraîche et un contrôle neuf n'effacent pas cette décision. Le dossier garde le fait que la réparation avait été jugée trop chère. Chiffrez cette voiture-là.",
        "Një makinë mund të bëhet përsëri e ligjshme për rrugë pasi sigurimi ka paguar. Boja e re dhe një kontroll i ri nuk e fshijnë atë vendim. Shënimi e mban faktin që riparimi atëherë u gjykua shumë i shtrenjtë. Çmoje si atë makinë.",
        "Auto może znów być legalne na drodze po wypłacie ubezpieczyciela. Świeży lakier i nowe badanie nie kasują tej decyzji. Zapis trzyma fakt, że naprawa była wtedy uznana za zbyt drogą. Wyceniaj właśnie to auto.",
        "O mașină poate fi din nou legală pe drum după ce asigurătorul a plătit. Vopseaua nouă și o inspecție nouă nu șterg decizia. Înregistrarea păstrează faptul că reparația a fost judecată prea scumpă atunci. Prețuiește mașina asta.",
        "Кола може отново да е законна за пътя, след като застрахователят е платил. Прясната боя и нов преглед не трият това решение. Записът пази факта, че ремонтът тогава е бил сметнат за твърде скъп. Оценявайте точно тази кола.",
        "მანქანა შეიძლება ისევ კანონიერი გახდეს გზაზე, მას შემდეგ რაც მზღვეველმა გადაიხადა. ახალი საღებავი და ახალი შემოწმება იმ გადაწყვეტილებას არ შლის. ჩანაწერი ინახავს, რომ რემონტი მაშინ ძალიან ძვირად ჩათვალეს. ამ მანქანის ფასი ამ მანქანაზე დააყენეთ.",
        "قد تعود السيارة قانونية على الطريق بعد أن دفع المؤمن. الطلاء الجديد والفحص الجديد لا يمحوان القرار. السجل يُبقي أن التصليح حُكم عليه حينها بأنه أغلى مما يستحق. سعّر هذه السيارة كما هي.",
        "Авто може знову бути законним на дорозі після виплати страховика. Свіжа фарба і новий огляд не стирають цього рішення. Запис тримає факт, що ремонт тоді визнали надто дорогим. Оцінюйте саме це авто.",
        "Машина может снова быть законной на дороге после выплаты страховщика. Свежая краска и новый осмотр не стирают это решение. Запись хранит факт, что ремонт тогда признали слишком дорогим. Оценивайте именно эту машину.",
        "保险公司赔付之后，车可以再合法上路。新漆和一次新检测抹不掉那个决定。记录留着当时维修被判定太贵这件事。按这辆车的实情给它定价。",
      ),
    },
    {
      h: L(
        "Read it before you book the trip",
        "Lesen Sie das, bevor Sie die Fahrt buchen",
        "Léelo antes de sacar el billete",
        "Lisez-le avant de prendre le trajet",
        "Lexoje para se të nisesh rrugës",
        "Przeczytaj, zanim kupisz bilet",
        "Citește-l înainte să-ți cumperi biletul",
        "Прочетете го, преди да вземете билета",
        "წაიკითხეთ, სანამ ბილეთს აიღებთ",
        "اقرأ ذلك قبل أن تحجز الرحلة",
        "Прочитайте це до квитка",
        "Прочитайте это до билета",
        "买票之前先读这条记录",
      ),
      p: L(
        "These cars are often rebuilt far from where you live, then advertised locally. The photos look straight. The file is the part you can read from home. If the insurer wrote the car off, you already know the main fact. You do not need the fare to learn it.",
        "Solche Autos werden oft weit weg von Ihnen wieder aufgebaut und dann lokal inseriert. Die Fotos wirken gerade. Die Akte können Sie von zu Hause lesen. Hat der Versicherer das Auto abgeschrieben, kennen Sie schon die Hauptsache. Dafür brauchen Sie die Fahrkarte nicht.",
        "Estos coches suelen reconstruirse lejos de donde vives y luego anunciarse cerca. Las fotos se ven rectas. El archivo es la parte que lees desde casa. Si el seguro dio el coche por perdido, ya sabes el dato principal. No necesitas el billete para enterarte.",
        "Ces voitures sont souvent reconstruites loin de chez vous, puis annoncées sur place. Les photos paraissent droites. Le dossier se lit depuis la maison. Si l'assureur a déclaré la voiture perdue, vous connaissez déjà le fait principal. Le trajet ne sert pas à l'apprendre.",
        "Këto makina shpesh riparohen larg nga vendi ku jeton, pastaj shpallën pranë. Fotot duken të drejta. Raporti është ajo që e lexon nga shtëpia. Nëse sigurimi e ka nxjerrë makinën jashtë, faktin kryesor e di tashmë. Nuk të duhet bileta për ta mësuar.",
        "Takie auta często odbudowuje się daleko od ciebie, a potem ogłasza na miejscu. Zdjęcia wyglądają prosto. Plik czytasz z domu. Jeśli ubezpieczyciel spisał auto, znasz już główną rzecz. Bilet nie jest do tego potrzebny.",
        "Mașinile astea sunt adesea reconstruite departe de tine, apoi anunțate local. Pozele par drepte. Dosarul e partea pe care o citești de acasă. Dacă asigurătorul a casat mașina, știi deja faptul principal. Nu ai nevoie de bilet ca să-l afli.",
        "Тези коли често се възстановяват далеч от вас и после се обявяват наблизо. Снимките изглеждат прави. Файлът се чете от вкъщи. Ако застрахователят е отписал колата, вече знаете главното. Билетът не ви трябва, за да го научите.",
        "ასეთ მანქანებს ხშირად შორს აღადგენენ, შემდეგ ადგილობრივად აქვეყნებენ. ფოტოები სწორად გამოიყურება. საქმე სახლიდან იკითხება. თუ მზღვეველმა მანქანა ჩამოწერა, მთავარი ფაქტი უკვე იცით. ბილეთი ამის გასაგებად არ გჭირდებათ.",
        "هذه السيارات غالباً تُعاد بناؤها بعيداً عنك ثم تُعلن محلياً. الصور تبدو مستقيمة. الملف هو ما تقرأه من البيت. إذا شطب المؤمن السيارة فقد عرفت الأمر الرئيسي. لا تحتاج الأجرة لتعرفه.",
        "Такі авто часто відновлюють далеко від вас, а потім оголошують поруч. Фото виглядають рівно. Файл читається з дому. Якщо страховик списав авто, головний факт уже відомий. Квиток для цього не потрібен.",
        "Такие машины часто восстанавливают далеко от вас, а потом объявляют рядом. Фото выглядят ровно. Файл читается из дома. Если страховщик списал машину, главный факт уже известен. Билет для этого не нужен.",
        "这类车常常在离你很远的地方修好，再在本地登广告。照片看起来很直。这份记录你可以在家里读。如果保险公司已经报废这辆车，主要事实你已经知道了。不必为了这件事买车票。",
      ),
    },
  ],
  usa: [
    {
      h: L(
        "Convert the miles before you compare",
        "Rechnen Sie die Meilen um, bevor Sie vergleichen",
        "Convierte las millas antes de comparar",
        "Convertissez les miles avant de comparer",
        "Ktheji miljet para se t'i krahasosh",
        "Przelicz mile, zanim porównasz",
        "Convertește milele înainte să compari",
        "Превърнете милите, преди да сравнявате",
        "შეადარებამდე მილები გადაიყვანეთ",
        "حوّل الأميال قبل أن تقارن",
        "Переведіть милі, перш ніж порівнювати",
        "Переведите мили, прежде чем сравнивать",
        "比较之前先把英里换算好",
      ),
      p: L(
        "80,000 miles is about 129,000 kilometres. If the advert uses kilometres and the old paper uses miles, write both figures in the same unit before you call the car lightly used. A seller who leaves the miles standing as if they were kilometres is describing a shorter life than the car had.",
        "80.000 Meilen sind etwa 129.000 Kilometer. Steht die Anzeige in Kilometern und das alte Papier in Meilen, schreiben Sie beide Werte in derselben Einheit, bevor Sie das Auto für wenig gefahren halten. Wer die Meilen stehen lässt, als wären sie Kilometer, beschreibt ein kürzeres Leben, als das Auto hatte.",
        "80.000 millas son unos 129.000 kilómetros. Si el anuncio va en kilómetros y el papel viejo en millas, escribe las dos cifras en la misma unidad antes de llamar al coche poco usado. Un vendedor que deja las millas como si fueran kilómetros describe una vida más corta de la que el coche tuvo.",
        "80 000 miles font environ 129 000 kilomètres. Si l'annonce est en kilomètres et l'ancien papier en miles, écrivez les deux chiffres dans la même unité avant de dire que la voiture a peu roulé. Un vendeur qui laisse les miles comme s'il s'agissait de kilomètres décrit une vie plus courte que celle de la voiture.",
        "80.000 milje janë rreth 129.000 kilometra. Nëse shpallja është në kilometra dhe letra e vjetër në milje, shkruaji të dyja në të njëjtën njësi para se ta quash makinën pak të përdorur. Shitësi që i lë miljet sikur të ishin kilometra po tregon një jetë më të shkurtër nga ajo që ka pasur makina.",
        "80 000 mil to około 129 000 kilometrów. Jeśli ogłoszenie jest w kilometrach, a stary papier w milach, zapisz obie liczby w tej samej jednostce, zanim nazwiesz auto mało jeżdżonym. Sprzedawca, który zostawia mile tak, jakby były kilometrami, opisuje krótsze życie, niż auto miało.",
        "80.000 de mile sunt cam 129.000 de kilometri. Dacă anunțul e în kilometri și hârtia veche în mile, scrie ambele cifre în aceeași unitate înainte să spui că mașina e puțin folosită. Un vânzător care lasă milele de parcă ar fi kilometri descrie o viață mai scurtă decât a avut mașina.",
        "80 000 мили са около 129 000 километра. Ако обявата е в километри, а старата хартия в мили, запишете и двете в една мерна единица, преди да наречете колата малко карана. Продавач, който оставя милите сякаш са километри, описва по-кратък живот, отколкото колата е имала.",
        "80 000 მილი დაახლოებით 129 000 კილომეტრია. თუ განცხადება კილომეტრებშია, ძველი ფურცელი კი მილებში, ერთსა და იმავე ერთეულში ჩაწერეთ, სანამ მანქანას ნაკლებად ნამყიდს უწოდებთ. გამყიდველი, რომელიც მილებს კილომეტრებად ტოვებს, უფრო მოკლე ცხოვრებას აღწერს, ვიდრე მანქანას ჰქონდა.",
        "80,000 ميل تقريباً 129,000 كيلومتر. إذا كان الإعلان بالكيلومتر والورقة القديمة بالأميال، اكتب الرقمين بالوحدة نفسها قبل أن تسمّي السيارة قليلة الاستعمال. بائع يترك الأميال وكأنها كيلومترات يصف عمراً أقصر مما عاشته السيارة.",
        "80 000 миль це близько 129 000 кілометрів. Якщо оголошення в кілометрах, а старий папір у милях, запишіть обидві цифри в одній одиниці, перш ніж назвати авто мало їждженим. Продавець, який лишає милі так, ніби це кілометри, описує коротше життя, ніж авто мало.",
        "80 000 миль это около 129 000 километров. Если объявление в километрах, а старая бумага в милях, запишите обе цифры в одной единице, прежде чем назвать машину мало езженной. Продавец, который оставляет мили так, будто это километры, описывает более короткую жизнь, чем была у машины.",
        "8 万英里大约是 12.9 万公里。如果广告用公里，旧文件用英里，在你说这车开得少之前，先把两个数字换成同一单位。卖家把英里原样当成公里，是在把这辆车说得比实际更少跑。",
      ),
    },
    {
      h: L(
        "The American note stays after the plates change",
        "Der amerikanische Vermerk bleibt nach dem Kennzeichenwechsel",
        "La nota americana sigue cuando cambian las placas",
        "La mention américaine reste après le changement de plaques",
        "Shënimi amerikan mbetet edhe pas ndërrimit të targave",
        "Amerykańska adnotacja zostaje po zmianie tablic",
        "Nota americană rămâne după schimbarea plăcuțelor",
        "Американската бележка остава след смяната на номерата",
        "ამერიკული შენიშვნა ნომრების შეცვლის შემდეგაც რჩება",
        "الملاحظة الأمريكية تبقى بعد تغيير اللوحات",
        "Американська позначка лишається після зміни номерів",
        "Американская пометка остаётся после смены номеров",
        "换了牌，美国那边的记号还在",
      ),
      p: L(
        "Local registration often starts a clean page. Flood, a write-off and a rebuild stay on the record from the state that insured the car. Ask which state the car came from, then read that file. A new plate in your country does not rewrite the American one.",
        "Die lokale Zulassung fängt oft auf einer leeren Seite an. Flut, Totalschaden und Wiederaufbau bleiben in der Akte des Staates, der das Auto versichert hat. Fragen Sie, aus welchem Staat das Auto kommt, und lesen Sie diese Akte. Ein neues Kennzeichen bei Ihnen schreibt die amerikanische Akte nicht um.",
        "La matriculación local suele empezar en una página limpia. Inundación, pérdida total y reconstrucción se quedan en el registro del estado que aseguró el coche. Pregunta de qué estado vino y lee ese archivo. Una placa nueva en tu país no reescribe la americana.",
        "L'immatriculation locale commence souvent sur une page blanche. Inondation, perte totale et reconstruction restent dans le dossier de l'État qui a assuré la voiture. Demandez de quel État elle vient, puis lisez ce dossier. Une plaque neuve chez vous ne réécrit pas le dossier américain.",
        "Regjistrimi lokal shpesh nis me një faqe të pastër. Përmbytja, dëmtimi total dhe rindërtimi mbeten te shteti që e ka siguruar makinën. Pyet nga cili shtet ka ardhur, pastaj lexoje atë regjistër. Një targë e re te ti nuk e rishkruan atë amerikanen.",
        "Lokalna rejestracja często zaczyna czystą stronę. Powódź, szkoda całkowita i odbudowa zostają w aktach stanu, który ubezpieczył auto. Zapytaj, z którego stanu auto przyjechało, i przeczytaj te akta. Nowa tablica u ciebie nie przepisuje amerykańskiej.",
        "Înmatricularea locală începe adesea pe o pagină curată. Inundația, dauna totală și reconstrucția rămân în dosarul statului care a asigurat mașina. Întreabă din ce stat a venit, apoi citește dosarul ăla. O plăcuță nouă la tine nu rescrie dosarul american.",
        "Местната регистрация често започва на чиста страница. Наводнение, тотал и възстановяване остават в записа на щата, който е застраховал колата. Попитайте от кой щат е дошла и прочетете това досие. Нов номер при вас не пренаписва американския.",
        "ადგილობრივი რეგისტრაცია ხშირად სუფთა გვერდით იწყება. წყალდიდობა, ჩამოწერა და აღდგენა იმ შტატის ჩანაწერში რჩება, რომელმაც მანქანა დააზღვია. ჰკითხეთ, რომელი შტატიდან მოვიდა, და ის საქმე წაიკითხეთ. ახალი ნომერი თქვენთან ამერიკულს არ გადაწერს.",
        "التسجيل المحلي يبدأ غالباً بصفحة نظيفة. الفيضان والخسارة الكاملة وإعادة البناء تبقى في سجل الولاية التي أمّنت السيارة. اسأل من أي ولاية جاءت ثم اقرأ ذلك الملف. لوحة جديدة في بلدك لا تعيد كتابة الملف الأمريكي.",
        "Місцева реєстрація часто починає чисту сторінку. Повінь, тотал і відбудова лишаються в записі штату, який страхував авто. Запитайте, з якого штату воно приїхало, і прочитайте ту справу. Новий номер у вас не переписує американський.",
        "Местная регистрация часто начинает чистую страницу. Наводнение, тотал и восстановление остаются в записи штата, который страховал машину. Спросите, из какого штата она приехала, и прочитайте то дело. Новый номер у вас не переписывает американский.",
        "本地登记常常从空白页开始。水淹、全损和重建还在承保那个州的记录里。先问这辆车来自哪个州，再读那份档案。你这里的新牌照不会改写美国那边的那一页。",
      ),
    },
  ],
  korea: [
    {
      h: L(
        "The grade is only the headline",
        "Die Note ist nur die Überschrift",
        "La nota es solo el titular",
        "La cote n'est que le titre",
        "Nota është vetëm titulli",
        "Ocena to tylko nagłówek",
        "Nota e doar titlul",
        "Оценката е само заглавието",
        "შეფასება მხოლოდ სათაურია",
        "التقييم مجرد عنوان",
        "Оцінка це лише заголовок",
        "Оценка это только заголовок",
        "评分只是标题",
      ),
      p: L(
        "A letter or a number on a Korean sheet is the first line, not the whole page. Under it you usually get the kilometres and short notes on panels, paint and replaced parts. Buyers who stop at the grade miss the lines that change the price.",
        "Ein Buchstabe oder eine Zahl auf einem koreanischen Bogen ist die erste Zeile, nicht die ganze Seite. Darunter stehen meist die Kilometer und kurze Vermerke zu Blechen, Lack und getauschten Teilen. Wer bei der Note aufhört, übersieht die Zeilen, die den Preis ändern.",
        "Una letra o un número en una ficha coreana es la primera línea, no la página. Debajo suelen estar los kilómetros y notas cortas sobre paneles, pintura y piezas cambiadas. Quien se queda en la nota se pierde las líneas que cambian el precio.",
        "Une lettre ou un chiffre sur une fiche coréenne est la première ligne, pas la page. Dessous se trouvent en général les kilomètres et de courtes notes sur les panneaux, la peinture et les pièces changées. Qui s'arrête à la cote manque les lignes qui changent le prix.",
        "Një shkronjë ose një numër në fletën koreane është rreshti i parë, jo gjithë faqja. Poshtë zakonisht janë kilometrat dhe shënime të shkurtra për panelet, bojën dhe pjesët e ndërruara. Kush ndalet te nota, i humb rreshtat që e ndryshojnë çmimin.",
        "Litera albo liczba na koreańskiej karcie to pierwsza linijka, nie cała strona. Pod spodem zwykle są kilometry i krótkie uwagi o blachach, lakierze i wymienionych częściach. Kto staje na ocenie, pomija linijki, które zmieniają cenę.",
        "O literă sau un număr pe fișa coreeană e primul rând, nu pagina. Sub el sunt de obicei kilometrii și note scurte despre panouri, vopsea și piese schimbate. Cine se oprește la notă pierde rândurile care schimbă prețul.",
        "Буква или число на корейския лист е първият ред, не цялата страница. Под него обикновено са километрите и кратки бележки за панели, боя и сменени части. Който спре на оценката, пропуска редовете, които сменят цената.",
        "ასო ან რიცხვი კორეულ ფურცელზე პირველი სტრიქონია, არა მთელი გვერდი. ქვემოთ ჩვეულებრივ კილომეტრები და მოკლე შენიშვნებია პანელებზე, საღებავსა და შეცვლილ ნაწილებზე. ვინც შეფასებაზე ჩერდება, იმ სტრიქონებს აცდება, რომლებიც ფასს ცვლის.",
        "حرف أو رقم على الورقة الكورية هو السطر الأول، لا الصفحة كلها. تحته عادة الكيلومترات وملاحظات قصيرة عن الألواح والطلاء والقطع المستبدلة. من يتوقف عند التقييم يفوّت الأسطر التي تغيّر السعر.",
        "Літера чи число на корейському листі це перший рядок, не вся сторінка. Під ним зазвичай кілометри і короткі нотатки про панелі, фарбу і замінені деталі. Хто зупиняється на оцінці, пропускає рядки, які змінюють ціну.",
        "Буква или число на корейском листе это первая строка, не вся страница. Под ней обычно километры и короткие заметки о панелях, краске и заменённых деталях. Кто останавливается на оценке, пропускает строки, которые меняют цену.",
        "韩国拍卖单上的一个字母或数字，只是第一行，不是整页。下面通常还有公里，以及板件、油漆和换过零件的短注。只看评分的人，会漏掉真正改价格的那几行。",
      ),
    },
    {
      h: L(
        "Ask for the date on the sheet",
        "Fragen Sie nach dem Datum auf dem Bogen",
        "Pide la fecha de la ficha",
        "Demandez la date sur la fiche",
        "Kërko datën mbi fletë",
        "Poproś o datę na karcie",
        "Cere data de pe fișă",
        "Поискайте датата на листа",
        "ფურცელზე თარიღი მოითხოვეთ",
        "اطلب التاريخ على الورقة",
        "Попросіть дату на листі",
        "Попросите дату на листе",
        "要拍卖单上的日期",
      ),
      p: L(
        "A sheet from the week the car was sold in Korea is more useful than a screenshot with the date cut off. The car has been driven, stored and repaired since then. Put the sheet's date next to the advert's date. The kilometres should make sense across that gap. They should not jump backwards.",
        "Ein Bogen aus der Woche, in der das Auto in Korea verkauft wurde, ist nützlicher als ein Screenshot ohne Datum. Seitdem wurde das Auto gefahren, abgestellt und repariert. Legen Sie das Datum des Bogens neben das der Anzeige. Die Kilometer müssen über diese Zeit Sinn ergeben. Sie dürfen nicht rückwärts springen.",
        "Una ficha de la semana en que el coche se vendió en Corea vale más que una captura con la fecha cortada. Desde entonces el coche se condujo, se guardó y se reparó. Pon la fecha de la ficha junto a la del anuncio. Los kilómetros tienen que tener sentido en ese hueco. No deben saltar hacia atrás.",
        "Une fiche de la semaine où la voiture a été vendue en Corée est plus utile qu'une capture dont la date est coupée. Depuis, la voiture a roulé, stationné et été réparée. Mettez la date de la fiche à côté de celle de l'annonce. Les kilomètres doivent tenir sur cet écart. Ils ne doivent pas reculer.",
        "Një fletë nga java kur makina u shit në Kore është më e dobishme se një foto pa datë. Që atëherë makina është drejtuar, është mbajtur e ndalur dhe është riparuar. Vëre datën e fletës pranë datës së shpalljes. Kilometrat duhet të kenë kuptim në atë hapësirë. Nuk duhet të kthehen prapa.",
        "Karta z tygodnia, w którym auto sprzedano w Korei, jest bardziej użyteczna niż zrzut z obciętą datą. Od tamtej pory auto jeździło, stało i było naprawiane. Połóż datę karty obok daty ogłoszenia. Kilometry muszą mieć sens w tej przerwie. Nie powinny skakać wstecz.",
        "O fișă din săptămâna în care mașina s-a vândut în Coreea e mai utilă decât o captură cu data tăiată. De atunci mașina a fost condusă, depozitată și reparată. Pune data fișei lângă data anunțului. Kilometrii trebuie să aibă sens peste golul ăsta. Nu trebuie să sară înapoi.",
        "Лист от седмицата, в която колата е продадена в Корея, е по-полезен от снимка с изрязана дата. Оттогава колата е карана, стояла е и е ремонтирана. Сложете датата на листа до датата на обявата. Километрите трябва да имат смисъл през този период. Не трябва да скачат назад.",
        "ფურცელი იმ კვირიდან, როცა მანქანა კორეაში გაიყიდა, უფრო სასარგებლოა, ვიდრე თარიღაწყვეტილი სურათი. მას შემდეგ მანქანა მოძრაობდა, იდგა და გარემონტდა. ფურცლის თარიღი განცხადების თარიღს გვერდით დააყენეთ. კილომეტრებს ამ შუალედში აზრი უნდა ჰქონდეს. უკან არ უნდა გადახტეს.",
        "ورقة من الأسبوع الذي بيعت فيه السيارة في كوريا أنفع من لقطة قُصّ تاريخها. منذ ذلك الحين قِيدت السيارة وخُزّنت وأُصلحت. ضع تاريخ الورقة بجانب تاريخ الإعلان. يجب أن تكون الكيلومترات منطقية عبر هذه الفجوة. لا ينبغي أن تقفز إلى الوراء.",
        "Лист з тижня, коли авто продали в Кореї, корисніший за знімок із відрізаною датою. Відтоді авто їздило, стояло і його ремонтували. Покладіть дату листа поруч із датою оголошення. Кілометри мають мати сенс на цьому проміжку. Вони не повинні стрибати назад.",
        "Лист с недели, когда машину продали в Корее, полезнее снимка с обрезанной датой. С тех пор машина ездила, стояла и её ремонтировали. Положите дату листа рядом с датой объявления. Километры должны иметь смысл на этом промежутке. Они не должны прыгать назад.",
        "车在韩国卖掉那一周的拍卖单，比一张裁掉日期的截图有用。从那以后这辆车又开过、停过、修过。把单上的日期和广告的日期放在一起。公里数在这段时间里应该说得通。它不该往回跳。",
      ),
    },
  ],
  "before-pay": [
    {
      figure: "/blog/inline/before-pay.jpg",
      h: L(
        "Same day, same 17 characters",
        "Gleicher Tag, dieselben 17 Zeichen",
        "El mismo día, los mismos 17 caracteres",
        "Le même jour, les mêmes 17 caractères",
        "E njëjta ditë, të njëjtat 17 shenja",
        "Ten sam dzień, te same 17 znaków",
        "Aceeași zi, aceleași 17 caractere",
        "Същият ден, същите 17 знака",
        "იგივე დღე, იგივე 17 ნიშანი",
        "اليوم نفسه، الرموز السبعة عشر نفسها",
        "Той самий день, ті самі 17 знаків",
        "Тот же день, те же 17 знаков",
        "同一天，同一串 17 位",
      ),
      p: L(
        "Get the VIN, open the report, and read mileage, damage and theft before the story changes or the seller asks for a transfer. Do it the day you receive the number. A report from last month, on a different car, does not cover this one.",
        "Holen Sie die VIN, öffnen Sie den Bericht und lesen Sie Kilometer, Schäden und Diebstahl, bevor sich die Geschichte ändert oder der Verkäufer eine Überweisung will. Tun Sie es am Tag, an dem Sie die Nummer bekommen. Ein Bericht vom Vormonat über ein anderes Auto deckt dieses hier nicht.",
        "Pide el VIN, abre el informe y lee kilómetros, daños y robo antes de que cambie la historia o el vendedor pida una transferencia. Hazlo el día que recibes el número. Un informe del mes pasado, de otro coche, no cubre este.",
        "Obtenez le VIN, ouvrez le rapport et lisez kilométrage, dommages et vol avant que le récit change ou que le vendeur demande un virement. Faites-le le jour où vous recevez le numéro. Un rapport du mois dernier, sur une autre voiture, ne couvre pas celle-ci.",
        "Merr VIN-in, hap raportin dhe lexo kilometrat, dëmet dhe vjedhjen para se të ndryshojë rrëfimi ose shitësi të kërkojë transfertën. Bëje ditën që e merr numrin. Një raport i muajit të kaluar, për një makinë tjetër, nuk e mbulon këtë.",
        "Weź VIN, otwórz raport i przeczytaj przebieg, szkody i kradzież, zanim zmieni się opowieść albo sprzedawca poprosi o przelew. Zrób to w dniu, w którym dostajesz numer. Raport z zeszłego miesiąca, o innym aucie, nie obejmuje tego.",
        "Ia VIN-ul, deschide raportul și citește kilometrii, daunele și furtul înainte să se schimbe povestea sau vânzătorul să ceară transferul. Fă-o în ziua în care primești numărul. Un raport de luna trecută, despre altă mașină, nu o acoperă pe asta.",
        "Вземете VIN, отворете отчета и прочетете пробег, щети и кражба, преди историята да се промени или продавачът да поиска превод. Направете го в деня, в който получавате номера. Отчет от миналия месец за друга кола не покрива тази.",
        "აიღეთ VIN, გახსენით ანგარიში და წაიკითხეთ კილომეტრები, ზიანი და ქურდობა, სანამ ამბავი შეიცვლება ან გამყიდველი გადარიცხვას ითხოვს. იმ დღეს გააკეთეთ, როცა ნომერს მიიღებთ. გასული თვის ანგარიში სხვა მანქანაზე ამას არ ფარავს.",
        "خذ رقم الهيكل، افتح التقرير واقرأ الكيلومترات والضرر والسرقة قبل أن تتغيّر الحكاية أو يطلب البائع تحويلاً. افعل ذلك في اليوم الذي يصلك فيه الرقم. تقرير الشهر الماضي عن سيارة أخرى لا يغطي هذه.",
        "Візьміть VIN, відкрийте звіт і прочитайте пробіг, пошкодження й викрадення, перш ніж історія зміниться або продавець попросить переказ. Зробіть це в день, коли отримуєте номер. Звіт минулого місяця про інше авто не покриває це.",
        "Возьмите VIN, откройте отчёт и прочитайте пробег, повреждения и угон, прежде чем история изменится или продавец попросит перевод. Сделайте это в день, когда получаете номер. Отчёт прошлого месяца о другой машине не покрывает эту.",
        "拿到 VIN，打开报告，在说法变掉、卖家要求转账之前，读公里、损伤和盗抢。拿到号码的当天就做。上个月另一辆车的报告，盖不住这一辆。",
      ),
    },
    {
      h: L(
        "The hurry is part of the price",
        "Die Eile gehört zum Preis",
        "La prisa forma parte del precio",
        "La précipitation fait partie du prix",
        "Ngutja është pjesë e çmimit",
        "Pośpiech jest częścią ceny",
        "Graba face parte din preț",
        "Бързането е част от цената",
        "ჩქარობა ფასის ნაწილია",
        "الاستعجال جزء من السعر",
        "Поспіх це частина ціни",
        "Спешка это часть цены",
        "催你的那句话，也算进价格里",
      ),
      p: L(
        "Another buyer, a boat leaving, a price that disappears tonight. Those lines are there to move the money before the file is open. A real car is still there tomorrow. If the seller cannot wait for you to read 17 characters, the hurry is what they are selling.",
        "Ein anderer Käufer, ein Schiff, das ablegt, ein Preis, der heute Nacht verschwindet. Diese Sätze sollen das Geld bewegen, bevor die Akte offen ist. Ein echtes Auto steht morgen noch da. Kann der Verkäufer nicht warten, bis Sie 17 Zeichen gelesen haben, ist die Eile das, was er verkauft.",
        "Otro comprador, un barco que sale, un precio que desaparece esta noche. Esas frases están para mover el dinero antes de que el archivo esté abierto. Un coche real sigue ahí mañana. Si el vendedor no puede esperar a que leas 17 caracteres, la prisa es lo que está vendiendo.",
        "Un autre acheteur, un bateau qui part, un prix qui disparaît ce soir. Ces phrases servent à faire bouger l'argent avant que le dossier soit ouvert. Une vraie voiture est encore là demain. Si le vendeur ne peut pas attendre que vous lisiez 17 caractères, c'est la précipitation qu'il vend.",
        "Një blerës tjetër, një anije që niset, një çmim që sonte zhduket. Këto fjali janë për të lëvizur paratë para se të hapet raporti. Një makinë e vërtetë është edhe nesër aty. Nëse shitësi nuk pret që të lexosh 17 shenja, ajo që shet është nxitimi.",
        "Inny kupujący, statek, który odpływa, cena, która znika dziś w nocy. Te zdania mają ruszyć pieniądze, zanim plik będzie otwarty. Prawdziwe auto będzie jutro. Jeśli sprzedawca nie może poczekać, aż przeczytasz 17 znaków, sprzedaje pośpiech.",
        "Alt cumpărător, o navă care pleacă, un preț care dispare diseară. Frazele astea mută banii înainte să fie deschis dosarul. O mașină reală e acolo și mâine. Dacă vânzătorul nu poate aștepta să citești 17 caractere, graba e ceea ce vinde.",
        "Друг купувач, кораб, който тръгва, цена, която изчезва довечера. Тези изречения местят парите, преди файлът да е отворен. Истинска кола е там и утре. Ако продавачът не може да изчака да прочетете 17 знака, бързането е това, което продава.",
        "სხვა მყიდველი, გემი, რომელიც მიდის, ფასი, რომელიც ღამით ქრება. ეს წინადადებები ფულს ამოძრავებს, სანამ საქმე ღიაა. ნამდვილი მანქანა ხვალაც იქ იქნება. თუ გამყიდველი ვერ ითმენს 17 ნიშნის წაკითხვას, ჩქარობას ყიდის.",
        "مشترٍ آخر، سفينة تغادر، سعر يختفي الليلة. هذه الجمل لتحريك المال قبل أن يُفتح الملف. السيارة الحقيقية تكون هناك غداً أيضاً. إذا لم يستطع البائع انتظار قراءتك 17 رمزاً، فالاستعجال هو ما يبيعه.",
        "Інший покупець, корабель, що відходить, ціна, яка зникає сьогодні вночі. Ці фрази рухають гроші, поки файл не відкрито. Справжнє авто буде і завтра. Якщо продавець не може зачекати, поки ви прочитаєте 17 знаків, він продає поспіх.",
        "Другой покупатель, судно, которое уходит, цена, которая исчезает сегодня ночью. Эти фразы двигают деньги, пока файл не открыт. Настоящая машина будет и завтра. Если продавец не может подождать, пока вы прочитаете 17 знаков, он продаёт спешку.",
        "还有别的买家，船要开了，今晚这个价就没了。这些话是为了在记录打开之前把钱挪走。一辆真的车明天还在。如果卖家等不及你读完 17 位，他卖的就是这个催促。",
      ),
    },
  ],
  accidents: [
    {
      figure: "/blog/inline/accidents.jpg",
      h: L(
        "Look where the advert does not",
        "Schauen Sie dorthin, wo die Anzeige nicht schaut",
        "Mira donde el anuncio no mira",
        "Regardez là où l'annonce ne regarde pas",
        "Shiko aty ku shpallja nuk tregon",
        "Patrz tam, gdzie ogłoszenie nie patrzy",
        "Uită-te unde anunțul nu se uită",
        "Погледнете там, където обявата не гледа",
        "ნახეთ იქ, სადაც განცხადება არ იყურება",
        "انظر حيث لا ينظر الإعلان",
        "Дивіться туди, куди оголошення не дивиться",
        "Смотрите туда, куда объявление не смотрит",
        "看广告没拍到的地方",
      ),
      p: L(
        "A light under the bonnet, along the rail and around the bolt heads, shows fresh paint, cracked sealer and parts that do not match. You will not diagnose the car in a car park. You can see enough to ask for the record before you pay.",
        "Eine Lampe unter der Haube, entlang des Trägers und um die Schraubenköpfe zeigt frischen Lack, rissige Dichtmasse und Teile, die nicht zusammenpassen. Sie diagnostizieren das Auto nicht auf dem Parkplatz. Sie sehen genug, um die Akte zu verlangen, bevor Sie zahlen.",
        "Una luz bajo el capó, a lo largo del larguero y alrededor de las cabezas de los tornillos, muestra pintura fresca, sellador agrietado y piezas que no coinciden. No vas a diagnosticar el coche en el aparcamiento. Ves lo bastante para pedir el registro antes de pagar.",
        "Une lampe sous le capot, le long du longeron et autour des têtes de vis, montre une peinture fraîche, un mastic fissuré et des pièces qui ne correspondent pas. Vous ne diagnostiquerez pas la voiture sur un parking. Vous en voyez assez pour demander le dossier avant de payer.",
        "Një dritë nën kapak, përgjatë traut dhe rreth kokave të bulonave, tregon bojë të freskët, izolues të plasaritur dhe pjesë që nuk përputhen. Nuk e diagnostikon makinën në parking. Sheh mjaftueshëm për të kërkuar raportin para se të paguash.",
        "Światło pod maską, wzdłuż belki i wokół łbów śrub, pokazuje świeży lakier, pęknięty uszczelniacz i części, które do siebie nie pasują. Nie zdiagnozujesz auta na parkingu. Widzisz dość, żeby poprosić o zapis, zanim zapłacisz.",
        "O lumină sub capotă, de-a lungul lonjeronului și în jurul capetelor de șurub, arată vopsea proaspătă, etanșant crăpat și piese care nu se potrivesc. Nu diagnostichezi mașina în parcare. Vezi destul cât să ceri dosarul înainte să plătești.",
        "Светлина под капака, по дължината на гредата и около главите на болтовете показва прясна боя, напукан уплътнител и части, които не пасват. Няма да диагностицирате колата на паркинга. Виждате достатъчно, за да поискате записа, преди да платите.",
        "შუქი კაპოტის ქვეშ, სხივის გასწვრივ და ჭანჭიკების თავებთან, ახალ საღებავს, გაბზარულ შემავსებელს და შეუსაბამო ნაწილებს აჩვენებს. პარკინგზე მანქანას ვერ დაადგენთ. საკმარისს ხედავთ, რომ გადახდამდე ჩანაწერი მოითხოვოთ.",
        "ضوء تحت الغطاء، على طول العارضة وحول رؤوس البراغي، يُظهر طلاءً جديداً وحشواً متشققاً وقطعاً لا تتطابق. لن تشخّص السيارة في الموقف. ترى ما يكفي لتطلب السجل قبل أن تدفع.",
        "Світло під капотом, уздовж балки і навколо головок болтів, показує свіжу фарбу, тріснутий герметик і деталі, які не пасують. На парковці ви авто не діагностуєте. Ви бачите достатньо, щоб попросити запис до оплати.",
        "Свет под капотом, вдоль балки и вокруг головок болтов, показывает свежую краску, треснувший герметик и детали, которые не совпадают. На парковке вы машину не диагностируете. Вы видите достаточно, чтобы попросить запись до оплаты.",
        "手电照引擎盖下面、纵梁和螺栓头周围，能看见新漆、裂开的密封胶和对不上的零件。你不会在停车场把这辆车确诊完。你看得到的，已经够你在付钱之前把记录要来。",
      ),
    },
    {
      h: L(
        "The damage photos stay in the file",
        "Die Schadensfotos bleiben in der Akte",
        "Las fotos del daño se quedan en el archivo",
        "Les photos des dégâts restent dans le dossier",
        "Fotot e dëmit mbeten në raport",
        "Zdjęcia szkody zostają w pliku",
        "Fotografiile daunei rămân în dosar",
        "Снимките на щетата остават във файла",
        "ზიანის ფოტოები საქმეში რჩება",
        "صور الضرر تبقى في الملف",
        "Фото пошкодження лишаються у файлі",
        "Фото повреждения остаются в файле",
        "损伤当天的照片留在记录里",
      ),
      p: L(
        "Paint hides a crease. The photo from the day of the hit does not. When the report includes those pictures, look at what was bent, not only at whether the car shines in the advert. A rail and a bumper skin are different repairs and different prices.",
        "Lack verdeckt eine Falte. Das Foto vom Tag des Schadens nicht. Wenn der Bericht diese Bilder enthält, schauen Sie, was verbogen war, nicht nur, ob das Auto in der Anzeige glänzt. Ein Träger und eine Stoßfängerhaut sind verschiedene Reparaturen und verschiedene Preise.",
        "La pintura tapa un pliegue. La foto del día del golpe no. Si el informe incluye esas imágenes, mira qué estaba doblado, no solo si el coche brilla en el anuncio. Un larguero y una piel de parachoques son reparaciones distintas y precios distintos.",
        "La peinture cache un pli. La photo du jour du choc, non. Quand le rapport contient ces images, regardez ce qui était tordu, pas seulement si la voiture brille dans l'annonce. Un longeron et une peau de pare-chocs sont des réparations différentes et des prix différents.",
        "Boja e fsheh një rrudhë. Fotoja e ditës së goditjes jo. Kur raporti i ka ato foto, shiko çfarë është përkulur, jo vetëm nëse makina shkëlqen në shpallje. Një tra dhe një parakolp i jashtëm janë riparime të ndryshme dhe çmime të ndryshme.",
        "Lakier kryje zagięcie. Zdjęcie z dnia uderzenia nie. Gdy raport ma te zdjęcia, patrz, co było wygięte, a nie tylko czy auto błyszczy w ogłoszeniu. Belka i skóra zderzaka to inne naprawy i inne ceny.",
        "Vopseaua ascunde o cută. Poza din ziua loviturii nu. Când raportul are acele imagini, uită-te la ce era îndoit, nu doar dacă mașina strălucește în anunț. Un lonjeron și o coajă de bară sunt reparații diferite și prețuri diferite.",
        "Боята крие гънка. Снимката от деня на удара не. Когато отчетът има тези снимки, гледайте какво е било огънато, не само дали колата блести в обявата. Гредата и обвивката на бронята са различни ремонти и различни цени.",
        "საღებავი ნაკეცს მალავს. დარტყმის დღის ფოტო არა. როცა ანგარიშში ეს სურათებია, ნახეთ რა იყო მოხრილი, არა მხოლოდ ის, ანათებს თუ არა მანქანა განცხადებაში. სხივი და ბამპერის გარსი სხვადასხვა რემონტია და სხვადასხვა ფასი.",
        "الطلاء يخفي تجعيدة. صورة يوم الضربة لا. حين يحتوي التقرير هذه الصور، انظر إلى ما كان مثنياً، لا فقط إن كانت السيارة تلمع في الإعلان. العارضة وقشرة الصادم تصليحان مختلفان وسعران مختلفان.",
        "Фарба ховає згин. Фото з дня удару ні. Коли у звіті є ці знімки, дивіться, що було погнуте, а не лише чи блищить авто в оголошенні. Балка і оболонка бампера це різні ремонти і різні ціни.",
        "Краска прячет складку. Фото со дня удара нет. Когда в отчёте есть эти снимки, смотрите, что было погнуто, а не только блестит ли машина в объявлении. Балка и оболочка бампера это разные ремонты и разные цены.",
        "漆能盖住一道褶。碰撞当天的照片盖不住。报告里有这些照片时，看弯的是什么，别只看车在广告里亮不亮。纵梁和保险杠皮，是两种修理，也是两种价钱。",
      ),
    },
  ],
  stolen: [
    {
      h: L(
        "Legal here, flagged somewhere else",
        "Hier zugelassen, anderswo gemeldet",
        "Legal aquí, marcado en otro sitio",
        "En règle ici, signalée ailleurs",
        "Ligjore këtu, e shënuar diku tjetër",
        "Legalne tutaj, oznaczone gdzie indziej",
        "Legală aici, semnalată în altă parte",
        "Законна тук, отбелязана другаде",
        "კანონიერი აქ, სხვაგან მონიშნული",
        "قانونية هنا ومُعلَّمة في مكان آخر",
        "Законне тут, позначене деінде",
        "Законная здесь, в розыске в другом месте",
        "在这里合法，在别处被标了",
      ),
      p: L(
        "A car can have local plates and a local inspection and still sit on a stolen-vehicle list in the country it left. The advert will show the plates. The check compares the chassis number with those lists. Plates are issued by the office in front of you. They do not cancel a flag written earlier.",
        "Ein Auto kann lokale Kennzeichen und eine lokale Prüfung haben und trotzdem im Herkunftsland als gestohlen geführt werden. Die Anzeige zeigt die Kennzeichen. Die Prüfung legt die Fahrgestellnummer auf diese Listen. Kennzeichen stellt das Amt vor Ort aus. Sie löschen keinen älteren Eintrag.",
        "Un coche puede tener placas locales y una inspección local y seguir en una lista de robados en el país del que salió. El anuncio mostrará las placas. La comprobación compara el número de chasis con esas listas. Las placas las da la oficina de aquí. No borran una marca escrita antes.",
        "Une voiture peut avoir des plaques locales et un contrôle local et rester sur une liste de véhicules volés dans le pays qu'elle a quitté. L'annonce montrera les plaques. Le contrôle compare le numéro de châssis à ces listes. Les plaques sont délivrées par le bureau devant vous. Elles n'annulent pas une mention plus ancienne.",
        "Një makinë mund të ketë targa vendore dhe kontroll vendor dhe prapë të qëndrojë në një listë makinash të vjedhura në vendin nga ka ardhur. Shpallja tregon targat. Kontrolli e krahason numrin e shasisë me ato lista. Targat i jep zyra para teje. Ato nuk e fshijnë një shënim të shkruar më parë.",
        "Auto może mieć lokalne tablice i lokalne badanie i nadal figurować na liście kradzionych w kraju, z którego wyjechało. Ogłoszenie pokaże tablice. Sprawdzenie zestawia numer nadwozia z tymi listami. Tablice wydaje urząd, który masz przed sobą. Nie kasują wcześniejszego wpisu.",
        "O mașină poate avea plăcuțe locale și o inspecție locală și tot să stea pe o listă de vehicule furate în țara din care a plecat. Anunțul va arăta plăcuțele. Verificarea compară numărul de șasiu cu listele alea. Plăcuțele le dă biroul din fața ta. Ele nu anulează un semn scris mai devreme.",
        "Кола може да има местни номера и местен преглед и пак да стои в списък за откраднати в страната, от която е тръгнала. Обявата ще покаже номерата. Проверката сверява номера на шасито с тези списъци. Номерата ги дава службата пред вас. Те не трият по-ранен запис.",
        "მანქანას შეიძლება ჰქონდეს ადგილობრივი ნომრები და ადგილობრივი შემოწმება და მაინც იდგეს მოპარულთა სიაში იმ ქვეყანაში, საიდანაც წამოვიდა. განცხადება ნომრებს აჩვენებს. შემოწმება შასის ნომერს იმ სიებს ადარებს. ნომრებს თქვენს წინ მყოფი სამსახური გასცემს. ადრე დაწერილ ნიშანს ისინი არ შლიან.",
        "قد تحمل السيارة لوحات محلية وفحصاً محلياً وتبقى على قائمة سيارات مسروقة في البلد الذي غادرته. الإعلان سيُظهر اللوحات. الفحص يقارن رقم الهيكل بتلك القوائم. اللوحات تصدُرها الجهة التي أمامك. وهي لا تلغي علامة كُتبت قبل ذلك.",
        "Авто може мати місцеві номери і місцевий огляд і все одно стояти в списку викрадених у країні, з якої виїхало. Оголошення покаже номери. Перевірка звіряє номер шасі з тими списками. Номери видає установа перед вами. Вони не скасовують раніший запис.",
        "Машина может иметь местные номера и местный осмотр и всё равно стоять в списке угнанных в стране, из которой она уехала. Объявление покажет номера. Проверка сверяет номер шасси с этими списками. Номера выдаёт учреждение перед вами. Они не отменяют более раннюю запись.",
        "一辆车可以有本地牌照和本地年检，同时仍在它离开的那个国家的失窃名单上。广告会给你看牌照。核查是拿车架号去对那些名单。牌照是你面前这个机构发的。它取消不了更早写下的那条标记。",
      ),
    },
    {
      h: L(
        "You want the clear answer too",
        "Sie wollen auch das klare Ergebnis",
        "También quieres la respuesta limpia",
        "Vous voulez aussi la réponse claire",
        "E do edhe përgjigjen e pastër",
        "Chcesz też czystej odpowiedzi",
        "Vrei și răspunsul curat",
        "Искате и чистия отговор",
        "სუფთა პასუხიც გინდათ",
        "تريد الإجابة النظيفة أيضاً",
        "Вам потрібна і чиста відповідь",
        "Вам нужен и чистый ответ",
        "干净的那句回答，你也需要",
      ),
      p: L(
        "Most cars you look at will not be stolen. Opening the check writes that down, and it shows mileage and damage in the same file. You are not paying for a single word. You are paying so a stolen chassis does not arrive with a tidy story.",
        "Die meisten Autos, die Sie ansehen, sind nicht gestohlen. Die Prüfung schreibt das auf und zeigt Kilometer und Schäden in derselben Akte. Sie zahlen nicht für ein einzelnes Wort. Sie zahlen, damit ein gestohlenes Fahrgestell nicht mit einer sauberen Geschichte ankommt.",
        "La mayoría de los coches que miras no estarán robados. Abrir la comprobación lo deja escrito y muestra kilómetros y daños en el mismo archivo. No pagas por una sola palabra. Pagas para que un chasis robado no llegue con una historia pulcra.",
        "La plupart des voitures que vous regardez ne sont pas volées. Ouvrir le contrôle l'écrit, et montre kilométrage et dommages dans le même dossier. Vous ne payez pas pour un seul mot. Vous payez pour qu'un châssis volé n'arrive pas avec une histoire propre.",
        "Shumica e makinave që sheh nuk janë të vjedhura. Hapja e kontrollit e lë të shkruar, dhe tregon kilometrat dhe dëmet në të njëjtin raport. Nuk paguan për një fjalë të vetme. Paguan që një shasi e vjedhur të mos vijë me një histori të pastër.",
        "Większość aut, które oglądasz, nie jest kradziona. Otwarcie sprawdzenia zapisuje to i pokazuje przebieg oraz szkody w tym samym pliku. Nie płacisz za jedno słowo. Płacisz, żeby kradzione nadwozie nie przyszło ze schludną historią.",
        "Majoritatea mașinilor pe care le vezi nu sunt furate. Deschiderea verificării scrie asta și arată kilometrii și daunele în același dosar. Nu plătești pentru un singur cuvânt. Plătești ca un șasiu furat să nu vină cu o poveste îngrijită.",
        "Повечето коли, които гледате, не са откраднати. Отварянето на проверката го записва и показва пробег и щети в същия файл. Не плащате за една дума. Плащате, за да не дойде откраднато шаси със спретната история.",
        "მანქანების უმეტესობა, რომელსაც უყურებთ, მოპარული არ არის. შემოწმების გახსნა ამას წერს და გარბენსა და ზიანს იმავე საქმეში აჩვენებს. ერთ სიტყვაში არ იხდით. იმაში იხდით, რომ მოპარული შასი მოწესრიგებული ამბით არ მოვიდეს.",
        "معظم السيارات التي تنظر إليها ليست مسروقة. فتح الفحص يكتب ذلك ويُظهر الكيلومترات والضرر في الملف نفسه. أنت لا تدفع مقابل كلمة واحدة. تدفع كي لا يصل هيكل مسروق بحكاية مرتبة.",
        "Більшість авто, які ви дивитеся, не викрадені. Відкриття перевірки це записує і показує пробіг та пошкодження в тому самому файлі. Ви платите не за одне слово. Ви платите, щоб викрадене шасі не прийшло з охайною історією.",
        "Большинство машин, которые вы смотрите, не в угоне. Открытие проверки это записывает и показывает пробег и повреждения в том же файле. Вы платите не за одно слово. Вы платите, чтобы угнанное шасси не пришло с аккуратной историей.",
        "你看的大多数车并没有被盗。打开核查是把这件事写下来，并在同一份记录里看到公里和损伤。你不是只为一句话付钱。你付钱，是为了让一个被盗的车架号不会带着一份整齐的故事出现。",
      ),
    },
  ],
  cost: [
    {
      figure: "/blog/inline/cost.jpg",
      h: L(
        "The fare is the first bill",
        "Die Fahrkarte ist die erste Rechnung",
        "El billete es la primera factura",
        "Le trajet est la première facture",
        "Bileta është fatura e parë",
        "Bilet to pierwszy rachunek",
        "Biletul e prima factură",
        "Билетът е първата сметка",
        "ბილეთი პირველი ანგარიშია",
        "الأجرة أول فاتورة",
        "Квиток це перший рахунок",
        "Билет это первый счёт",
        "路费是第一张账单",
      ),
      p: L(
        "Fuel or a ticket to see the car is already money. Add the hours, the deposit you might not see again, and the repair if the kilometres were wrong. A history check is the small bill that sits in front of those. If the car is the wrong one, you skip the rest.",
        "Sprit oder eine Fahrkarte, um das Auto zu sehen, ist schon Geld. Dazu die Stunden, die Anzahlung, die Sie vielleicht nicht wiedersehen, und die Reparatur, wenn die Kilometer nicht gestimmt haben. Die Prüfung ist die kleine Rechnung davor. Ist das Auto das falsche, lassen Sie den Rest aus.",
        "La gasolina o el billete para ver el coche ya es dinero. Suma las horas, la señal que quizá no vuelvas a ver y la reparación si los kilómetros no eran reales. La comprobación es la factura pequeña que va delante. Si el coche no es el bueno, te saltas el resto.",
        "L'essence ou le billet pour voir la voiture est déjà de l'argent. Ajoutez les heures, les arrhes que vous ne reverrez peut-être pas, et la réparation si les kilomètres étaient faux. Le contrôle est la petite facture qui vient avant. Si la voiture n'est pas la bonne, vous sautez le reste.",
        "Karburanti ose bileta për ta parë makinën tashmë janë para. Shtoji orët, kaparin që mund të mos e rishohësh, dhe riparimin nëse kilometrat nuk ishin të vërtetë. Kontrolli i historisë është fatura e vogël që qëndron para tyre. Nëse makina nuk është e duhura, e kalon pjesën tjetër.",
        "Paliwo albo bilet, żeby zobaczyć auto, to już pieniądze. Dolicz godziny, zadatek, którego możesz nie zobaczyć, i naprawę, jeśli kilometry były złe. Sprawdzenie historii jest małym rachunkiem z przodu. Jeśli auto nie jest tym właściwym, resztę pomijasz.",
        "Benzina sau biletul ca să vezi mașina sunt deja bani. Adaugă orele, avansul pe care poate nu-l mai vezi și reparația dacă kilometrii erau greșiți. Verificarea istoricului e factura mică din față. Dacă mașina nu e cea bună, sari peste rest.",
        "Горивото или билетът, за да видите колата, вече са пари. Добавете часовете, капарото, което може да не видите отново, и ремонта, ако километрите са били грешни. Проверката на историята е малката сметка отпред. Ако колата не е правилната, пропускате останалото.",
        "საწვავი ან ბილეთი მანქანის სანახავად უკვე ფულია. დაამატეთ საათები, ავანსი, რომელიც შეიძლება აღარ ნახოთ, და რემონტი, თუ კილომეტრები არასწორი იყო. ისტორიის შემოწმება პატარა ანგარიშია მათ წინ. თუ მანქანა არასწორია, დანარჩენს გამოტოვებთ.",
        "الوقود أو التذكرة لرؤية السيارة مال بالفعل. أضف الساعات والعربون الذي قد لا تراه ثانية والتصليح إذا كانت الكيلومترات غير صحيحة. فحص التاريخ هو الفاتورة الصغيرة التي تقف أمامها. إن لم تكن السيارة المناسبة، تتجاوز الباقي.",
        "Пальне чи квиток, щоб побачити авто, це вже гроші. Додайте години, завдаток, який можете не побачити знову, і ремонт, якщо кілометри були не ті. Перевірка історії це маленький рахунок попереду. Якщо авто не те, решту ви пропускаєте.",
        "Топливо или билет, чтобы увидеть машину, это уже деньги. Добавьте часы, задаток, который можете не увидеть снова, и ремонт, если километры были не те. Проверка истории это маленький счёт впереди. Если машина не та, остальное вы пропускаете.",
        "去看车的油费或车票已经是钱。再加上时间、可能拿不回来的定金，还有公里不对时的修理。历史核查是排在这些前面的那张小账单。车不对，后面的都不用花。",
      ),
    },
    {
      h: L(
        "Put the fee next to a gearbox",
        "Legen Sie die Gebühr neben ein Getriebe",
        "Pon la tarifa junto a una caja de cambios",
        "Posez le prix à côté d'une boîte de vitesses",
        "Vëre tarifën pranë një kambioje",
        "Połóż opłatę obok skrzyni biegów",
        "Pune taxa lângă o cutie de viteze",
        "Сложете таксата до скоростна кутия",
        "საფასური გადაცემათა კოლოფის გვერდით დააყენეთ",
        "ضع الرسم بجانب علبة تروس",
        "Покладіть плату поруч із коробкою передач",
        "Положите плату рядом с коробкой передач",
        "把这笔费用和一台变速箱放在一起看",
      ),
      p: L(
        "People argue about the price of a report and then buy a gearbox, a head gasket or a week of trouble on a car the file would have described. Put the fee next to one of those bills. The report is there so the expensive bill stays a choice.",
        "Menschen streiten über den Preis eines Berichts und kaufen dann ein Getriebe, eine Kopfdichtung oder eine Woche Ärger für ein Auto, das die Akte beschrieben hätte. Legen Sie die Gebühr neben eine dieser Rechnungen. Der Bericht ist dazu da, dass die teure Rechnung eine Wahl bleibt.",
        "La gente discute el precio de un informe y luego compra una caja de cambios, una junta de culata o una semana de problemas en un coche que el archivo habría descrito. Pon la tarifa junto a una de esas facturas. El informe está para que la factura cara siga siendo una elección.",
        "On discute le prix d'un rapport, puis on achète une boîte de vitesses, un joint de culasse ou une semaine d'ennuis sur une voiture que le dossier aurait décrite. Posez le prix à côté de l'une de ces factures. Le rapport sert à ce que la facture chère reste un choix.",
        "Njerëzit debatojnë për çmimin e një raporti dhe pastaj blejnë një kambio, një copë koke ose një javë telashe për një makinë që raporti do ta kishte përshkruar. Vëre tarifën pranë njërës prej këtyre faturave. Raporti është që fatura e shtrenjtë të mbetet zgjedhje.",
        "Ludzie kłócą się o cenę raportu, a potem kupują skrzynię, uszczelkę głowicy albo tydzień kłopotu przy aucie, które plik by opisał. Połóż opłatę obok jednego z tych rachunków. Raport jest po to, żeby drogi rachunek został wyborem.",
        "Oamenii se ceartă pe prețul unui raport și apoi cumpără o cutie de viteze, o garnitură de chiulasă sau o săptămână de necaz pe o mașină pe care dosarul ar fi descris-o. Pune taxa lângă una din facturile alea. Raportul e ca factura scumpă să rămână o alegere.",
        "Хората спорят за цената на отчета и после купуват скоростна кутия, гарнитура на главата или седмица неприятности за кола, която файлът би описал. Сложете таксата до една от тези сметки. Отчетът е, за да остане скъпата сметка избор.",
        "ხალხი ანგარიშის ფასზე კამათობს და მერე ყიდულობს გადაცემათა კოლოფს, თავის შუასადებს ან ერთ კვირა პრობლემას მანქანაზე, რომელსაც საქმე აღწერდა. საფასური ერთ-ერთ ამ ანგარიშს გვერდით დააყენეთ. ანგარიში იმისთვისაა, რომ ძვირი ანგარიში არჩევანად დარჩეს.",
        "يتجادل الناس في سعر التقرير ثم يشترون علبة تروس أو حشية رأس أو أسبوع متاعب لسيارة كان الملف سيصفها. ضع الرسم بجانب إحدى تلك الفواتير. التقرير موجود كي تبقى الفاتورة الغالية خياراً.",
        "Люди сперечаються про ціну звіту, а потім купують коробку, прокладку головки чи тиждень клопоту на авто, яке файл описав би. Покладіть плату поруч з одним із цих рахунків. Звіт для того, щоб дорогий рахунок лишився вибором.",
        "Люди спорят о цене отчёта, а потом покупают коробку, прокладку головки или неделю хлопот на машине, которую файл описал бы. Положите плату рядом с одним из этих счетов. Отчёт для того, чтобы дорогой счёт остался выбором.",
        "人们会争论一份报告的价钱，然后为一辆记录本来就能说明的车去买变速箱、气缸垫，或者惹上一周的麻烦。把这笔费用和其中一张账单放在一起。报告在这里，是为了让那张贵的账单仍然是你可以选的。",
      ),
    },
  ],
};
