import { demoCarPhotoUrl } from "./demo-car-photos";

export interface DemoCar {
  vin: string;
  name: string;
  year: number;
  origin: "USA" | "Korea" | "Germany" | "China" | "Japan" | "UAE";
  flagImg: string;
  photo: string;
  score: number;
  mileage: number;
  unit: "mi" | "km";
  accidents: number;
  owners: number;
  salvage: boolean;
  stolen: boolean;
  condition: "CLEAN" | "CAUTION" | "RISK";
}

// Photos: JPEGs in public/demo-cars (served as /demo-cars/*; refreshed on build).
// Manual refresh: node artifacts/verifykm/scripts/fetch-demo-car-photos.mjs
export const ALL_CARS: DemoCar[] = [
  /* Korea */
  {
    vin: "KM8R3DGE3PU812456",
    name: "Hyundai Tucson",
    year: 2023,
    origin: "Korea",
    flagImg: "kr",
    unit: "km",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("hyundai-tucson.jpg"),
    score: 9.6,
    mileage: 24_800,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "KNAE251D5M6129044",
    name: "Kia K8",
    year: 2022,
    origin: "Korea",
    flagImg: "kr",
    unit: "km",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("kia-k8.jpg"),
    score: 9.3,
    mileage: 41_200,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "KNDPM3AC9K7583241",
    name: "Kia Sportage",
    year: 2019,
    origin: "Korea",
    flagImg: "kr",
    unit: "km",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("kia-sportage.jpg"),
    score: 6.4,
    mileage: 138_600,
    accidents: 2,
    owners: 3,
    salvage: false,
    stolen: false,
  },
  {
    vin: "KMHEC41CBGA156782",
    name: "Hyundai Grandeur",
    year: 2017,
    origin: "Korea",
    flagImg: "kr",
    unit: "km",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("hyundai-grandeur.jpg"),
    score: 5.9,
    mileage: 192_400,
    accidents: 1,
    owners: 4,
    salvage: false,
    stolen: false,
  },
  {
    vin: "KNAE251D5J6038429",
    name: "Kia Carnival",
    year: 2016,
    origin: "Korea",
    flagImg: "kr",
    unit: "km",
    condition: "RISK",
    photo: demoCarPhotoUrl("kia-carnival.jpg"),
    score: 3.4,
    mileage: 264_000,
    accidents: 3,
    owners: 5,
    salvage: true,
    stolen: false,
  },

  /* USA */
  {
    vin: "2T3P1RFV8NW214892",
    name: "Toyota RAV4",
    year: 2022,
    origin: "USA",
    flagImg: "us",
    unit: "mi",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("toyota-rav4.jpg"),
    score: 9.5,
    mileage: 19_400,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "7FARS4H49NE038214",
    name: "Honda CR-V",
    year: 2021,
    origin: "USA",
    flagImg: "us",
    unit: "mi",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("honda-crv.jpg"),
    score: 9.1,
    mileage: 32_800,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "1FTEW1E50JKF08392",
    name: "Ford F-150",
    year: 2018,
    origin: "USA",
    flagImg: "us",
    unit: "mi",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("ford-f150.jpg"),
    score: 6.7,
    mileage: 118_200,
    accidents: 2,
    owners: 3,
    salvage: false,
    stolen: false,
  },
  {
    vin: "1N4AL3AP8JC142876",
    name: "Nissan Altima",
    year: 2017,
    origin: "USA",
    flagImg: "us",
    unit: "mi",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("nissan-altima.jpg"),
    score: 6.1,
    mileage: 97_500,
    accidents: 1,
    owners: 4,
    salvage: false,
    stolen: false,
  },
  {
    vin: "1G11C5SL4EF287341",
    name: "Chevrolet Malibu",
    year: 2014,
    origin: "USA",
    flagImg: "us",
    unit: "mi",
    condition: "RISK",
    photo: demoCarPhotoUrl("chevy-malibu.jpg"),
    score: 3.1,
    mileage: 156_800,
    accidents: 3,
    owners: 4,
    salvage: true,
    stolen: false,
  },

  /* Germany — popular imports */
  {
    vin: "WBA8E9G50MNU51284",
    name: "BMW 320i",
    year: 2021,
    origin: "Germany",
    flagImg: "de",
    unit: "km",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("bmw-320i.jpg"),
    score: 9.2,
    mileage: 38_400,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "WDDWF4HB9KR284719",
    name: "Mercedes-Benz C 220d",
    year: 2019,
    origin: "Germany",
    flagImg: "de",
    unit: "km",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("mercedes-c-class.jpg"),
    score: 6.8,
    mileage: 112_500,
    accidents: 1,
    owners: 2,
    salvage: false,
    stolen: false,
  },
  {
    vin: "WVWZZZ5NZJW847291",
    name: "Volkswagen Tiguan",
    year: 2018,
    origin: "Germany",
    flagImg: "de",
    unit: "km",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("vw-tiguan.jpg"),
    score: 6.2,
    mileage: 146_800,
    accidents: 1,
    owners: 3,
    salvage: false,
    stolen: false,
  },

  /* China — domestic EVs */
  {
    vin: "LFVVB9E75N3012847",
    name: "BYD Han EV",
    year: 2023,
    origin: "China",
    flagImg: "cn",
    unit: "km",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("byd-han-ev.jpg"),
    score: 9.4,
    mileage: 18_600,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "LJNBBABA5PA012847",
    name: "NIO ET5",
    year: 2022,
    origin: "China",
    flagImg: "cn",
    unit: "km",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("nio-et5.jpg"),
    score: 9.1,
    mileage: 32_400,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "LC0C76C49R0123456",
    name: "BYD Seal",
    year: 2023,
    origin: "China",
    flagImg: "cn",
    unit: "km",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("byd-seal.jpg"),
    score: 6.6,
    mileage: 54_200,
    accidents: 1,
    owners: 2,
    salvage: false,
    stolen: false,
  },
  {
    vin: "LXPV2A4C8MA012345",
    name: "XPeng P7",
    year: 2021,
    origin: "China",
    flagImg: "cn",
    unit: "km",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("xpeng-p7.jpg"),
    score: 6.2,
    mileage: 78_900,
    accidents: 1,
    owners: 3,
    salvage: false,
    stolen: false,
  },
  {
    vin: "L6T79T2E3ND012345",
    name: "Zeekr 001",
    year: 2022,
    origin: "China",
    flagImg: "cn",
    unit: "km",
    condition: "RISK",
    photo: demoCarPhotoUrl("zeekr-001.jpg"),
    score: 3.6,
    mileage: 112_000,
    accidents: 2,
    owners: 4,
    salvage: true,
    stolen: false,
  },

  /* Japan — domestic auction / export market */
  {
    vin: "JTDKN3DU5A0123456",
    name: "Toyota Prius",
    year: 2021,
    origin: "Japan",
    flagImg: "jp",
    unit: "km",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("toyota-prius.jpg"),
    score: 9.1,
    mileage: 42_600,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "JHMCG5650C0123456",
    name: "Honda Civic",
    year: 2020,
    origin: "Japan",
    flagImg: "jp",
    unit: "km",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("honda-civic.jpg"),
    score: 8.7,
    mileage: 58_200,
    accidents: 0,
    owners: 2,
    salvage: false,
    stolen: false,
  },
  {
    vin: "JN1BJ1CW5LW123456",
    name: "Nissan Qashqai",
    year: 2022,
    origin: "Japan",
    flagImg: "jp",
    unit: "km",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("nissan-qashqai.jpg"),
    score: 6.5,
    mileage: 91_400,
    accidents: 1,
    owners: 2,
    salvage: false,
    stolen: false,
  },
  {
    vin: "JF1VA2L65G9823456",
    name: "Subaru Forester",
    year: 2019,
    origin: "Japan",
    flagImg: "jp",
    unit: "km",
    condition: "RISK",
    photo: demoCarPhotoUrl("subaru-forester.jpg"),
    score: 4.1,
    mileage: 148_000,
    accidents: 2,
    owners: 3,
    salvage: true,
    stolen: false,
  },

  /* UAE — luxury imports */
  {
    vin: "WUAZZZFX7LN012345",
    name: "Audi R8",
    year: 2020,
    origin: "UAE",
    flagImg: "ae",
    unit: "km",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("audi-r8.jpg"),
    score: 9.5,
    mileage: 22_400,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "WP0AB2A99KS712345",
    name: "Porsche 911 Carrera",
    year: 2019,
    origin: "UAE",
    flagImg: "ae",
    unit: "km",
    condition: "CLEAN",
    photo: demoCarPhotoUrl("porsche-911.jpg"),
    score: 9.2,
    mileage: 31_800,
    accidents: 0,
    owners: 1,
    salvage: false,
    stolen: false,
  },
  {
    vin: "ZFF80AMA0J0234567",
    name: "Ferrari 488 GTB",
    year: 2017,
    origin: "UAE",
    flagImg: "ae",
    unit: "km",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("ferrari-488.jpg"),
    score: 6.5,
    mileage: 48_600,
    accidents: 1,
    owners: 2,
    salvage: false,
    stolen: false,
  },
  {
    vin: "ZHWUT5ZF4KLA01234",
    name: "Lamborghini Huracán",
    year: 2018,
    origin: "UAE",
    flagImg: "ae",
    unit: "km",
    condition: "CAUTION",
    photo: demoCarPhotoUrl("lamborghini-huracan.jpg"),
    score: 6.0,
    mileage: 36_200,
    accidents: 1,
    owners: 2,
    salvage: false,
    stolen: false,
  },
  {
    vin: "WDDWJ6EB5KA012345",
    name: "Mercedes-AMG GT",
    year: 2019,
    origin: "UAE",
    flagImg: "ae",
    unit: "km",
    condition: "RISK",
    photo: demoCarPhotoUrl("mercedes-amg-gt.jpg"),
    score: 3.2,
    mileage: 89_500,
    accidents: 2,
    owners: 3,
    salvage: true,
    stolen: false,
  },
];

export function carsForCountry(country?: "usa" | "korea" | "canada" | "china" | "japan" | "uae"): DemoCar[] {
  if (!country) return ALL_CARS;
  if (country === "korea") {
    return ALL_CARS.filter((c) => c.origin === "Korea" || c.origin === "Germany");
  }
  if (country === "canada") {
    return ALL_CARS.filter((c) => c.origin === "USA" || c.origin === "Germany");
  }
  if (country === "china") {
    return ALL_CARS.filter((c) => c.origin === "China");
  }
  if (country === "japan") {
    return ALL_CARS.filter((c) => c.origin === "Japan");
  }
  if (country === "uae") {
    return ALL_CARS.filter((c) => c.origin === "UAE");
  }
  return ALL_CARS.filter((c) => c.origin === "USA");
}

